package org.talend.datastewardship.server.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.9
 * Wed Apr 01 17:33:55 CST 2015
 * Generated source version: 2.2.9
 * 
 */
 
@WebService(targetNamespace = "http://ws.server.datastewardship.talend.org/", name = "TDSCWS")
@XmlSeeAlso({net.java.dev.jaxb.array.ObjectFactory.class, ObjectFactory.class})
public interface TDSCWS {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "echo", targetNamespace = "http://ws.server.datastewardship.talend.org/", className = "org.talend.datastewardship.server.ws.Echo")
    @WebMethod
    @ResponseWrapper(localName = "echoResponse", targetNamespace = "http://ws.server.datastewardship.talend.org/", className = "org.talend.datastewardship.server.ws.EchoResponse")
    public java.lang.String echo(
        @WebParam(name = "text", targetNamespace = "")
        java.lang.String text
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTask", targetNamespace = "http://ws.server.datastewardship.talend.org/", className = "org.talend.datastewardship.server.ws.GetTask")
    @WebMethod
    @ResponseWrapper(localName = "getTaskResponse", targetNamespace = "http://ws.server.datastewardship.talend.org/", className = "org.talend.datastewardship.server.ws.GetTaskResponse")
    public java.lang.String getTask(
        @WebParam(name = "taskID", targetNamespace = "")
        java.lang.String taskID
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSrcRecord", targetNamespace = "http://ws.server.datastewardship.talend.org/", className = "org.talend.datastewardship.server.ws.GetSrcRecord")
    @WebMethod
    @ResponseWrapper(localName = "getSrcRecordResponse", targetNamespace = "http://ws.server.datastewardship.talend.org/", className = "org.talend.datastewardship.server.ws.GetSrcRecordResponse")
    public java.util.List<net.java.dev.jaxb.array.StringArrayArray> getSrcRecord(
        @WebParam(name = "taskID", targetNamespace = "")
        java.lang.String taskID
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "searchTasks", targetNamespace = "http://ws.server.datastewardship.talend.org/", className = "org.talend.datastewardship.server.ws.SearchTasks")
    @WebMethod
    @ResponseWrapper(localName = "searchTasksResponse", targetNamespace = "http://ws.server.datastewardship.talend.org/", className = "org.talend.datastewardship.server.ws.SearchTasksResponse")
    public java.util.List<net.java.dev.jaxb.array.StringArray> searchTasks(
        @WebParam(name = "typeId", targetNamespace = "")
        java.lang.Integer typeId,
        @WebParam(name = "owner", targetNamespace = "")
        java.lang.String owner,
        @WebParam(name = "tagLabel", targetNamespace = "")
        java.lang.String tagLabel,
        @WebParam(name = "createTimeLowerBound", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar createTimeLowerBound,
        @WebParam(name = "createTimeUpperBound", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar createTimeUpperBound,
        @WebParam(name = "starNum", targetNamespace = "")
        java.lang.Integer starNum,
        @WebParam(name = "limit", targetNamespace = "")
        int limit,
        @WebParam(name = "status", targetNamespace = "")
        java.lang.String status
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findTask", targetNamespace = "http://ws.server.datastewardship.talend.org/", className = "org.talend.datastewardship.server.ws.FindTask")
    @WebMethod
    @ResponseWrapper(localName = "findTaskResponse", targetNamespace = "http://ws.server.datastewardship.talend.org/", className = "org.talend.datastewardship.server.ws.FindTaskResponse")
    public java.lang.String findTask(
        @WebParam(name = "srcRecordIdColumnName", targetNamespace = "")
        java.lang.String srcRecordIdColumnName,
        @WebParam(name = "srcRecordId", targetNamespace = "")
        java.lang.String srcRecordId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTaskModifiedAfter", targetNamespace = "http://ws.server.datastewardship.talend.org/", className = "org.talend.datastewardship.server.ws.GetTaskModifiedAfter")
    @WebMethod
    @ResponseWrapper(localName = "getTaskModifiedAfterResponse", targetNamespace = "http://ws.server.datastewardship.talend.org/", className = "org.talend.datastewardship.server.ws.GetTaskModifiedAfterResponse")
    public java.util.List<java.lang.String> getTaskModifiedAfter(
        @WebParam(name = "timestamp", targetNamespace = "")
        long timestamp
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getNumOfTasks", targetNamespace = "http://ws.server.datastewardship.talend.org/", className = "org.talend.datastewardship.server.ws.GetNumOfTasks")
    @WebMethod
    @ResponseWrapper(localName = "getNumOfTasksResponse", targetNamespace = "http://ws.server.datastewardship.talend.org/", className = "org.talend.datastewardship.server.ws.GetNumOfTasksResponse")
    public int getNumOfTasks(
        @WebParam(name = "owner", targetNamespace = "")
        java.lang.String owner,
        @WebParam(name = "status", targetNamespace = "")
        java.lang.String status
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTgtRecord", targetNamespace = "http://ws.server.datastewardship.talend.org/", className = "org.talend.datastewardship.server.ws.GetTgtRecord")
    @WebMethod
    @ResponseWrapper(localName = "getTgtRecordResponse", targetNamespace = "http://ws.server.datastewardship.talend.org/", className = "org.talend.datastewardship.server.ws.GetTgtRecordResponse")
    public java.util.List<net.java.dev.jaxb.array.StringArray> getTgtRecord(
        @WebParam(name = "taskID", targetNamespace = "")
        java.lang.String taskID
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteTasks", targetNamespace = "http://ws.server.datastewardship.talend.org/", className = "org.talend.datastewardship.server.ws.DeleteTasks")
    @WebMethod
    @ResponseWrapper(localName = "deleteTasksResponse", targetNamespace = "http://ws.server.datastewardship.talend.org/", className = "org.talend.datastewardship.server.ws.DeleteTasksResponse")
    public int deleteTasks(
        @WebParam(name = "typeId", targetNamespace = "")
        java.lang.Integer typeId,
        @WebParam(name = "owner", targetNamespace = "")
        java.lang.String owner,
        @WebParam(name = "tagLabel", targetNamespace = "")
        java.lang.String tagLabel,
        @WebParam(name = "createTimeLowerBound", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar createTimeLowerBound,
        @WebParam(name = "createTimeUpperBound", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar createTimeUpperBound,
        @WebParam(name = "starNum", targetNamespace = "")
        java.lang.Integer starNum,
        @WebParam(name = "limit", targetNamespace = "")
        int limit,
        @WebParam(name = "status", targetNamespace = "")
        java.lang.String status
    );

    @RequestWrapper(localName = "deleteTask", targetNamespace = "http://ws.server.datastewardship.talend.org/", className = "org.talend.datastewardship.server.ws.DeleteTask")
    @WebMethod
    @ResponseWrapper(localName = "deleteTaskResponse", targetNamespace = "http://ws.server.datastewardship.talend.org/", className = "org.talend.datastewardship.server.ws.DeleteTaskResponse")
    public void deleteTask(
        @WebParam(name = "taskID", targetNamespace = "")
        java.lang.String taskID
    );
}
