
package org.talend.datastewardship.server.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.9
 * Wed Apr 01 17:33:55 CST 2015
 * Generated source version: 2.2.9
 * 
 */

public final class TDSCWS_TDSCWSImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.server.datastewardship.talend.org/", "TDSCWS");

    private TDSCWS_TDSCWSImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = TDSCWS_Service.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        TDSCWS_Service ss = new TDSCWS_Service(wsdlURL, SERVICE_NAME);
        TDSCWS port = ss.getTDSCWSImplPort();  
        
        {
        System.out.println("Invoking echo...");
        java.lang.String _echo_text = "";
        java.lang.String _echo__return = port.echo(_echo_text);
        System.out.println("echo.result=" + _echo__return);


        }
        {
        System.out.println("Invoking getTask...");
        java.lang.String _getTask_taskID = "";
        java.lang.String _getTask__return = port.getTask(_getTask_taskID);
        System.out.println("getTask.result=" + _getTask__return);


        }
        {
        System.out.println("Invoking getSrcRecord...");
        java.lang.String _getSrcRecord_taskID = "";
        java.util.List<net.java.dev.jaxb.array.StringArrayArray> _getSrcRecord__return = port.getSrcRecord(_getSrcRecord_taskID);
        System.out.println("getSrcRecord.result=" + _getSrcRecord__return);


        }
        {
        System.out.println("Invoking searchTasks...");
        java.lang.Integer _searchTasks_typeId = null;
        java.lang.String _searchTasks_owner = "";
        java.lang.String _searchTasks_tagLabel = "";
        javax.xml.datatype.XMLGregorianCalendar _searchTasks_createTimeLowerBound = null;
        javax.xml.datatype.XMLGregorianCalendar _searchTasks_createTimeUpperBound = null;
        java.lang.Integer _searchTasks_starNum = null;
        int _searchTasks_limit = 0;
        java.lang.String _searchTasks_status = "";
        java.util.List<net.java.dev.jaxb.array.StringArray> _searchTasks__return = port.searchTasks(_searchTasks_typeId, _searchTasks_owner, _searchTasks_tagLabel, _searchTasks_createTimeLowerBound, _searchTasks_createTimeUpperBound, _searchTasks_starNum, _searchTasks_limit, _searchTasks_status);
        System.out.println("searchTasks.result=" + _searchTasks__return);


        }
        {
        System.out.println("Invoking findTask...");
        java.lang.String _findTask_srcRecordIdColumnName = "";
        java.lang.String _findTask_srcRecordId = "";
        java.lang.String _findTask__return = port.findTask(_findTask_srcRecordIdColumnName, _findTask_srcRecordId);
        System.out.println("findTask.result=" + _findTask__return);


        }
        {
        System.out.println("Invoking getTaskModifiedAfter...");
        long _getTaskModifiedAfter_timestamp = 0;
        java.util.List<java.lang.String> _getTaskModifiedAfter__return = port.getTaskModifiedAfter(_getTaskModifiedAfter_timestamp);
        System.out.println("getTaskModifiedAfter.result=" + _getTaskModifiedAfter__return);


        }
        {
        System.out.println("Invoking getNumOfTasks...");
        java.lang.String _getNumOfTasks_owner = "";
        java.lang.String _getNumOfTasks_status = "";
        int _getNumOfTasks__return = port.getNumOfTasks(_getNumOfTasks_owner, _getNumOfTasks_status);
        System.out.println("getNumOfTasks.result=" + _getNumOfTasks__return);


        }
        {
        System.out.println("Invoking getTgtRecord...");
        java.lang.String _getTgtRecord_taskID = "";
        java.util.List<net.java.dev.jaxb.array.StringArray> _getTgtRecord__return = port.getTgtRecord(_getTgtRecord_taskID);
        System.out.println("getTgtRecord.result=" + _getTgtRecord__return);


        }
        {
        System.out.println("Invoking deleteTasks...");
        java.lang.Integer _deleteTasks_typeId = null;
        java.lang.String _deleteTasks_owner = "";
        java.lang.String _deleteTasks_tagLabel = "";
        javax.xml.datatype.XMLGregorianCalendar _deleteTasks_createTimeLowerBound = null;
        javax.xml.datatype.XMLGregorianCalendar _deleteTasks_createTimeUpperBound = null;
        java.lang.Integer _deleteTasks_starNum = null;
        int _deleteTasks_limit = 0;
        java.lang.String _deleteTasks_status = "";
        int _deleteTasks__return = port.deleteTasks(_deleteTasks_typeId, _deleteTasks_owner, _deleteTasks_tagLabel, _deleteTasks_createTimeLowerBound, _deleteTasks_createTimeUpperBound, _deleteTasks_starNum, _deleteTasks_limit, _deleteTasks_status);
        System.out.println("deleteTasks.result=" + _deleteTasks__return);


        }
        {
        System.out.println("Invoking deleteTask...");
        java.lang.String _deleteTask_taskID = "";
        port.deleteTask(_deleteTask_taskID);


        }

        System.exit(0);
    }

}
