
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.talend.datastewardship.server.ws;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.9
 * Wed Apr 01 17:33:55 CST 2015
 * Generated source version: 2.2.9
 * 
 */

@javax.jws.WebService(
                      serviceName = "TDSCWS",
                      portName = "TDSCWSImplPort",
                      targetNamespace = "http://ws.server.datastewardship.talend.org/",
                      wsdlLocation = "http://192.168.32.63:8080/talendmdm/services/TDSCWS?wsdl",
                      endpointInterface = "org.talend.datastewardship.server.ws.TDSCWS")
                      
public class TDSCWSImpl implements TDSCWS {

    private static final Logger LOG = Logger.getLogger(TDSCWSImpl.class.getName());

    /* (non-Javadoc)
     * @see org.talend.datastewardship.server.ws.TDSCWS#echo(java.lang.String  text )*
     */
    public java.lang.String echo(java.lang.String text) { 
        LOG.info("Executing operation echo");
        System.out.println(text);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.talend.datastewardship.server.ws.TDSCWS#getTask(java.lang.String  taskID )*
     */
    public java.lang.String getTask(java.lang.String taskID) { 
        LOG.info("Executing operation getTask");
        System.out.println(taskID);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.talend.datastewardship.server.ws.TDSCWS#getSrcRecord(java.lang.String  taskID )*
     */
    public java.util.List<net.java.dev.jaxb.array.StringArrayArray> getSrcRecord(java.lang.String taskID) { 
        LOG.info("Executing operation getSrcRecord");
        System.out.println(taskID);
        try {
            java.util.List<net.java.dev.jaxb.array.StringArrayArray> _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.talend.datastewardship.server.ws.TDSCWS#searchTasks(java.lang.Integer  typeId ,)java.lang.String  owner ,)java.lang.String  tagLabel ,)javax.xml.datatype.XMLGregorianCalendar  createTimeLowerBound ,)javax.xml.datatype.XMLGregorianCalendar  createTimeUpperBound ,)java.lang.Integer  starNum ,)int  limit ,)java.lang.String  status )*
     */
    public java.util.List<net.java.dev.jaxb.array.StringArray> searchTasks(java.lang.Integer typeId,java.lang.String owner,java.lang.String tagLabel,javax.xml.datatype.XMLGregorianCalendar createTimeLowerBound,javax.xml.datatype.XMLGregorianCalendar createTimeUpperBound,java.lang.Integer starNum,int limit,java.lang.String status) { 
        LOG.info("Executing operation searchTasks");
        System.out.println(typeId);
        System.out.println(owner);
        System.out.println(tagLabel);
        System.out.println(createTimeLowerBound);
        System.out.println(createTimeUpperBound);
        System.out.println(starNum);
        System.out.println(limit);
        System.out.println(status);
        try {
            java.util.List<net.java.dev.jaxb.array.StringArray> _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.talend.datastewardship.server.ws.TDSCWS#findTask(java.lang.String  srcRecordIdColumnName ,)java.lang.String  srcRecordId )*
     */
    public java.lang.String findTask(java.lang.String srcRecordIdColumnName,java.lang.String srcRecordId) { 
        LOG.info("Executing operation findTask");
        System.out.println(srcRecordIdColumnName);
        System.out.println(srcRecordId);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.talend.datastewardship.server.ws.TDSCWS#getTaskModifiedAfter(long  timestamp )*
     */
    public java.util.List<java.lang.String> getTaskModifiedAfter(long timestamp) { 
        LOG.info("Executing operation getTaskModifiedAfter");
        System.out.println(timestamp);
        try {
            java.util.List<java.lang.String> _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.talend.datastewardship.server.ws.TDSCWS#getNumOfTasks(java.lang.String  owner ,)java.lang.String  status )*
     */
    public int getNumOfTasks(java.lang.String owner,java.lang.String status) { 
        LOG.info("Executing operation getNumOfTasks");
        System.out.println(owner);
        System.out.println(status);
        try {
            int _return = 0;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.talend.datastewardship.server.ws.TDSCWS#getTgtRecord(java.lang.String  taskID )*
     */
    public java.util.List<net.java.dev.jaxb.array.StringArray> getTgtRecord(java.lang.String taskID) { 
        LOG.info("Executing operation getTgtRecord");
        System.out.println(taskID);
        try {
            java.util.List<net.java.dev.jaxb.array.StringArray> _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.talend.datastewardship.server.ws.TDSCWS#deleteTasks(java.lang.Integer  typeId ,)java.lang.String  owner ,)java.lang.String  tagLabel ,)javax.xml.datatype.XMLGregorianCalendar  createTimeLowerBound ,)javax.xml.datatype.XMLGregorianCalendar  createTimeUpperBound ,)java.lang.Integer  starNum ,)int  limit ,)java.lang.String  status )*
     */
    public int deleteTasks(java.lang.Integer typeId,java.lang.String owner,java.lang.String tagLabel,javax.xml.datatype.XMLGregorianCalendar createTimeLowerBound,javax.xml.datatype.XMLGregorianCalendar createTimeUpperBound,java.lang.Integer starNum,int limit,java.lang.String status) { 
        LOG.info("Executing operation deleteTasks");
        System.out.println(typeId);
        System.out.println(owner);
        System.out.println(tagLabel);
        System.out.println(createTimeLowerBound);
        System.out.println(createTimeUpperBound);
        System.out.println(starNum);
        System.out.println(limit);
        System.out.println(status);
        try {
            int _return = 0;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.talend.datastewardship.server.ws.TDSCWS#deleteTask(java.lang.String  taskID )*
     */
    public void deleteTask(java.lang.String taskID) { 
        LOG.info("Executing operation deleteTask");
        System.out.println(taskID);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
