
package com.microsoft.schemas.xrm._2011.contracts.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.12
 * 2015-05-06T14:46:29.139+08:00
 * Generated source version: 2.7.12
 */

@WebFault(name = "OrganizationServiceFault", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts")
public class IOrganizationServiceRetrieveOrganizationServiceFaultFaultFaultMessage extends Exception {
    
    private com.microsoft.schemas.xrm._2011.contracts.OrganizationServiceFault organizationServiceFault;

    public IOrganizationServiceRetrieveOrganizationServiceFaultFaultFaultMessage() {
        super();
    }
    
    public IOrganizationServiceRetrieveOrganizationServiceFaultFaultFaultMessage(String message) {
        super(message);
    }
    
    public IOrganizationServiceRetrieveOrganizationServiceFaultFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public IOrganizationServiceRetrieveOrganizationServiceFaultFaultFaultMessage(String message, com.microsoft.schemas.xrm._2011.contracts.OrganizationServiceFault organizationServiceFault) {
        super(message);
        this.organizationServiceFault = organizationServiceFault;
    }

    public IOrganizationServiceRetrieveOrganizationServiceFaultFaultFaultMessage(String message, com.microsoft.schemas.xrm._2011.contracts.OrganizationServiceFault organizationServiceFault, Throwable cause) {
        super(message, cause);
        this.organizationServiceFault = organizationServiceFault;
    }

    public com.microsoft.schemas.xrm._2011.contracts.OrganizationServiceFault getFaultInfo() {
        return this.organizationServiceFault;
    }
}
