package com.microsoft.schemas.xrm._2011.contracts.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2015-05-06T14:46:29.208+08:00
 * Generated source version: 2.7.12
 * 
 */
@WebService(targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services", name = "IOrganizationService")
@XmlSeeAlso({org.datacontract.schemas._2004._07.system_collections.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class, com.microsoft.schemas.xrm._2011.metadata.ObjectFactory.class, com.microsoft.schemas.xrm._2013.metadata.ObjectFactory.class, com.microsoft.schemas.xrm._2012.contracts.ObjectFactory.class, com.microsoft.schemas.crm._2011.contracts.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, org.datacontract.schemas._2004._07.microsoft_crm_sdk.ObjectFactory.class, com.microsoft.schemas.xrm._2011.contracts.ObjectFactory.class, com.microsoft.schemas.xrm._2011.metadata.query.ObjectFactory.class, org.w3._2001.xmlschema.ObjectFactory.class, ObjectFactory.class, com.microsoft.schemas.xrm._2014.contracts.ObjectFactory.class, org.datacontract.schemas._2004._07.microsoft_xrm.ObjectFactory.class})
public interface IOrganizationService {

    @Action(input = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Update", output = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/UpdateResponse", fault = {@FaultAction(className = IOrganizationServiceUpdateOrganizationServiceFaultFaultFaultMessage.class, value = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/UpdateOrganizationServiceFaultFault")})
    @RequestWrapper(localName = "Update", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services", className = "com.microsoft.schemas.xrm._2011.contracts.services.Update")
    @WebMethod(operationName = "Update", action = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Update")
    @ResponseWrapper(localName = "UpdateResponse", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services", className = "com.microsoft.schemas.xrm._2011.contracts.services.UpdateResponse")
    public void update(
        @WebParam(name = "entity", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services")
        com.microsoft.schemas.xrm._2011.contracts.Entity entity
    ) throws IOrganizationServiceUpdateOrganizationServiceFaultFaultFaultMessage;

    @WebResult(name = "RetrieveResult", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services")
    @Action(input = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Retrieve", output = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/RetrieveResponse", fault = {@FaultAction(className = IOrganizationServiceRetrieveOrganizationServiceFaultFaultFaultMessage.class, value = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/RetrieveOrganizationServiceFaultFault")})
    @RequestWrapper(localName = "Retrieve", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services", className = "com.microsoft.schemas.xrm._2011.contracts.services.Retrieve")
    @WebMethod(operationName = "Retrieve", action = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Retrieve")
    @ResponseWrapper(localName = "RetrieveResponse", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services", className = "com.microsoft.schemas.xrm._2011.contracts.services.RetrieveResponse")
    public com.microsoft.schemas.xrm._2011.contracts.Entity retrieve(
        @WebParam(name = "entityName", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services")
        java.lang.String entityName,
        @WebParam(name = "id", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services")
        com.microsoft.schemas._2003._10.serialization.Guid id,
        @WebParam(name = "columnSet", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services")
        com.microsoft.schemas.xrm._2011.contracts.ColumnSet columnSet
    ) throws IOrganizationServiceRetrieveOrganizationServiceFaultFaultFaultMessage;

    @WebResult(name = "CreateResult", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services")
    @Action(input = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Create", output = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/CreateResponse", fault = {@FaultAction(className = IOrganizationServiceCreateOrganizationServiceFaultFaultFaultMessage.class, value = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/CreateOrganizationServiceFaultFault")})
    @RequestWrapper(localName = "Create", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services", className = "com.microsoft.schemas.xrm._2011.contracts.services.Create")
    @WebMethod(operationName = "Create", action = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Create")
    @ResponseWrapper(localName = "CreateResponse", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services", className = "com.microsoft.schemas.xrm._2011.contracts.services.CreateResponse")
    public com.microsoft.schemas._2003._10.serialization.Guid create(
        @WebParam(name = "entity", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services")
        com.microsoft.schemas.xrm._2011.contracts.Entity entity
    ) throws IOrganizationServiceCreateOrganizationServiceFaultFaultFaultMessage;

    @WebResult(name = "RetrieveMultipleResult", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services")
    @Action(input = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/RetrieveMultiple", output = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/RetrieveMultipleResponse", fault = {@FaultAction(className = IOrganizationServiceRetrieveMultipleOrganizationServiceFaultFaultFaultMessage.class, value = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/RetrieveMultipleOrganizationServiceFaultFault")})
    @RequestWrapper(localName = "RetrieveMultiple", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services", className = "com.microsoft.schemas.xrm._2011.contracts.services.RetrieveMultiple")
    @WebMethod(operationName = "RetrieveMultiple", action = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/RetrieveMultiple")
    @ResponseWrapper(localName = "RetrieveMultipleResponse", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services", className = "com.microsoft.schemas.xrm._2011.contracts.services.RetrieveMultipleResponse")
    public com.microsoft.schemas.xrm._2011.contracts.EntityCollection retrieveMultiple(
        @WebParam(name = "query", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services")
        com.microsoft.schemas.xrm._2011.contracts.QueryBase query
    ) throws IOrganizationServiceRetrieveMultipleOrganizationServiceFaultFaultFaultMessage;

    @Action(input = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Associate", output = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/AssociateResponse", fault = {@FaultAction(className = IOrganizationServiceAssociateOrganizationServiceFaultFaultFaultMessage.class, value = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/AssociateOrganizationServiceFaultFault")})
    @RequestWrapper(localName = "Associate", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services", className = "com.microsoft.schemas.xrm._2011.contracts.services.Associate")
    @WebMethod(operationName = "Associate", action = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Associate")
    @ResponseWrapper(localName = "AssociateResponse", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services", className = "com.microsoft.schemas.xrm._2011.contracts.services.AssociateResponse")
    public void associate(
        @WebParam(name = "entityName", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services")
        java.lang.String entityName,
        @WebParam(name = "entityId", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services")
        com.microsoft.schemas._2003._10.serialization.Guid entityId,
        @WebParam(name = "relationship", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services")
        com.microsoft.schemas.xrm._2011.contracts.Relationship relationship,
        @WebParam(name = "relatedEntities", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services")
        com.microsoft.schemas.xrm._2011.contracts.EntityReferenceCollection relatedEntities
    ) throws IOrganizationServiceAssociateOrganizationServiceFaultFaultFaultMessage;

    @Action(input = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Disassociate", output = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/DisassociateResponse", fault = {@FaultAction(className = IOrganizationServiceDisassociateOrganizationServiceFaultFaultFaultMessage.class, value = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/DisassociateOrganizationServiceFaultFault")})
    @RequestWrapper(localName = "Disassociate", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services", className = "com.microsoft.schemas.xrm._2011.contracts.services.Disassociate")
    @WebMethod(operationName = "Disassociate", action = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Disassociate")
    @ResponseWrapper(localName = "DisassociateResponse", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services", className = "com.microsoft.schemas.xrm._2011.contracts.services.DisassociateResponse")
    public void disassociate(
        @WebParam(name = "entityName", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services")
        java.lang.String entityName,
        @WebParam(name = "entityId", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services")
        com.microsoft.schemas._2003._10.serialization.Guid entityId,
        @WebParam(name = "relationship", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services")
        com.microsoft.schemas.xrm._2011.contracts.Relationship relationship,
        @WebParam(name = "relatedEntities", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services")
        com.microsoft.schemas.xrm._2011.contracts.EntityReferenceCollection relatedEntities
    ) throws IOrganizationServiceDisassociateOrganizationServiceFaultFaultFaultMessage;

    @WebResult(name = "ExecuteResult", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services")
    @Action(input = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Execute", output = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/ExecuteResponse", fault = {@FaultAction(className = IOrganizationServiceExecuteOrganizationServiceFaultFaultFaultMessage.class, value = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/ExecuteOrganizationServiceFaultFault")})
    @RequestWrapper(localName = "Execute", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services", className = "com.microsoft.schemas.xrm._2011.contracts.services.Execute")
    @WebMethod(operationName = "Execute", action = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Execute")
    @ResponseWrapper(localName = "ExecuteResponse", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services", className = "com.microsoft.schemas.xrm._2011.contracts.services.ExecuteResponse")
    public com.microsoft.schemas.xrm._2011.contracts.OrganizationResponse execute(
        @WebParam(name = "request", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services")
        com.microsoft.schemas.xrm._2011.contracts.OrganizationRequest request
    ) throws IOrganizationServiceExecuteOrganizationServiceFaultFaultFaultMessage;

    @Action(input = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Delete", output = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/DeleteResponse", fault = {@FaultAction(className = IOrganizationServiceDeleteOrganizationServiceFaultFaultFaultMessage.class, value = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/DeleteOrganizationServiceFaultFault")})
    @RequestWrapper(localName = "Delete", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services", className = "com.microsoft.schemas.xrm._2011.contracts.services.Delete")
    @WebMethod(operationName = "Delete", action = "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Delete")
    @ResponseWrapper(localName = "DeleteResponse", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services", className = "com.microsoft.schemas.xrm._2011.contracts.services.DeleteResponse")
    public void delete(
        @WebParam(name = "entityName", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services")
        java.lang.String entityName,
        @WebParam(name = "id", targetNamespace = "http://schemas.microsoft.com/xrm/2011/Contracts/Services")
        com.microsoft.schemas._2003._10.serialization.Guid id
    ) throws IOrganizationServiceDeleteOrganizationServiceFaultFaultFaultMessage;
}
