<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="TestServiceBinding"
		xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
		xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
		xmlns:xsd="http://www.w3.org/2001/XMLSchema"
		xmlns:svc="http://www.talend.org/service/"
		xmlns:tns="http://www.talend.org/service/binding/"
		targetNamespace="http://www.talend.org/service/binding/">

    <wsdl:import namespace="http://www.talend.org/service/" location="TestService.wsdl" />

	<wsdl:binding name="TestServiceBinding" type="svc:TestServicePortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="TestServiceOperation">
			<soap:operation soapAction="http://www.talend.org/service/TestServiceOperation" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
</wsdl:definitions>
