
/*
 * 
 */

package org.talend.datastewardship.server.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.9
 * Thu Jun 19 15:50:09 CST 2014
 * Generated source version: 2.2.9
 * 
 */


@WebServiceClient(name = "TDSCWS", 
                  wsdlLocation = "http://localhost:8180/org.talend.datastewardship/services/TDSCWS?wsdl",
                  targetNamespace = "http://ws.server.datastewardship.talend.org/") 
public class TDSCWS_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://ws.server.datastewardship.talend.org/", "TDSCWS");
    public final static QName TDSCWSImplPort = new QName("http://ws.server.datastewardship.talend.org/", "TDSCWSImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8180/org.talend.datastewardship/services/TDSCWS?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8180/org.talend.datastewardship/services/TDSCWS?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public TDSCWS_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TDSCWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TDSCWS_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns TDSCWS
     */
    @WebEndpoint(name = "TDSCWSImplPort")
    public TDSCWS getTDSCWSImplPort() {
        return super.getPort(TDSCWSImplPort, TDSCWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TDSCWS
     */
    @WebEndpoint(name = "TDSCWSImplPort")
    public TDSCWS getTDSCWSImplPort(WebServiceFeature... features) {
        return super.getPort(TDSCWSImplPort, TDSCWS.class, features);
    }

}
