
package com.netsuite.webservices.platform;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-05-08T11:20:33.866+08:00
 * Generated source version: 3.1.0
 */

@WebFault(name = "exceededRequestLimitFault", targetNamespace = "urn:faults_2014_2.platform.webservices.netsuite.com")
public class ExceededRequestLimitFault extends Exception {
    
    private com.netsuite.webservices.platform.faults.ExceededRequestLimitFault exceededRequestLimitFault;

    public ExceededRequestLimitFault() {
        super();
    }
    
    public ExceededRequestLimitFault(String message) {
        super(message);
    }
    
    public ExceededRequestLimitFault(String message, Throwable cause) {
        super(message, cause);
    }

    public ExceededRequestLimitFault(String message, com.netsuite.webservices.platform.faults.ExceededRequestLimitFault exceededRequestLimitFault) {
        super(message);
        this.exceededRequestLimitFault = exceededRequestLimitFault;
    }

    public ExceededRequestLimitFault(String message, com.netsuite.webservices.platform.faults.ExceededRequestLimitFault exceededRequestLimitFault, Throwable cause) {
        super(message, cause);
        this.exceededRequestLimitFault = exceededRequestLimitFault;
    }

    public com.netsuite.webservices.platform.faults.ExceededRequestLimitFault getFaultInfo() {
        return this.exceededRequestLimitFault;
    }
}
