
package com.netsuite.webservices.platform;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2015-04-08T13:30:12.672+08:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "invalidCredentialsFault", targetNamespace = "urn:faults_2014_2.platform.webservices.netsuite.com")
public class InvalidCredentialsFault extends Exception {
    
    private com.netsuite.webservices.platform.faults.InvalidCredentialsFault invalidCredentialsFault;

    public InvalidCredentialsFault() {
        super();
    }
    
    public InvalidCredentialsFault(String message) {
        super(message);
    }
    
    public InvalidCredentialsFault(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidCredentialsFault(String message, com.netsuite.webservices.platform.faults.InvalidCredentialsFault invalidCredentialsFault) {
        super(message);
        this.invalidCredentialsFault = invalidCredentialsFault;
    }

    public InvalidCredentialsFault(String message, com.netsuite.webservices.platform.faults.InvalidCredentialsFault invalidCredentialsFault, Throwable cause) {
        super(message, cause);
        this.invalidCredentialsFault = invalidCredentialsFault;
    }

    public com.netsuite.webservices.platform.faults.InvalidCredentialsFault getFaultInfo() {
        return this.invalidCredentialsFault;
    }
}
