
package com.netsuite.webservices.platform;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2015-04-08T13:30:12.712+08:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "invalidVersionFault", targetNamespace = "urn:faults_2014_2.platform.webservices.netsuite.com")
public class InvalidVersionFault extends Exception {
    
    private com.netsuite.webservices.platform.faults.InvalidVersionFault invalidVersionFault;

    public InvalidVersionFault() {
        super();
    }
    
    public InvalidVersionFault(String message) {
        super(message);
    }
    
    public InvalidVersionFault(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidVersionFault(String message, com.netsuite.webservices.platform.faults.InvalidVersionFault invalidVersionFault) {
        super(message);
        this.invalidVersionFault = invalidVersionFault;
    }

    public InvalidVersionFault(String message, com.netsuite.webservices.platform.faults.InvalidVersionFault invalidVersionFault, Throwable cause) {
        super(message, cause);
        this.invalidVersionFault = invalidVersionFault;
    }

    public com.netsuite.webservices.platform.faults.InvalidVersionFault getFaultInfo() {
        return this.invalidVersionFault;
    }
}
