package com.netsuite.webservices.platform;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2015-04-08T13:30:12.757+08:00
 * Generated source version: 2.7.7
 * 
 */
@WebServiceClient(name = "NetSuiteService", 
                  wsdlLocation = "/home/hg/桌面/netsuite_wsdl/wsdl/netsuite.wsdl",
                  targetNamespace = "urn:platform_2014_2.webservices.netsuite.com") 
public class NetSuiteService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:platform_2014_2.webservices.netsuite.com", "NetSuiteService");
    public final static QName NetSuitePort = new QName("urn:platform_2014_2.webservices.netsuite.com", "NetSuitePort");
    static {
        URL url = NetSuiteService.class.getResource("/home/hg/桌面/netsuite_wsdl/wsdl/netsuite.wsdl");
        if (url == null) {
            url = NetSuiteService.class.getClassLoader().getResource("/home/hg/桌面/netsuite_wsdl/wsdl/netsuite.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(NetSuiteService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "/home/hg/桌面/netsuite_wsdl/wsdl/netsuite.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public NetSuiteService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public NetSuiteService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NetSuiteService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public NetSuiteService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public NetSuiteService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public NetSuiteService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns NetSuitePortType
     */
    @WebEndpoint(name = "NetSuitePort")
    public NetSuitePortType getNetSuitePort() {
        return super.getPort(NetSuitePort, NetSuitePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NetSuitePortType
     */
    @WebEndpoint(name = "NetSuitePort")
    public NetSuitePortType getNetSuitePort(WebServiceFeature... features) {
        return super.getPort(NetSuitePort, NetSuitePortType.class, features);
    }

}
