/**
 * CountryOfOriginType.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.AddressDoctor.validator2.addInteractive.Interactive;

public class CountryOfOriginType implements java.io.Serializable {
    private java.lang.String _value_;
    private static java.util.HashMap _table_ = new java.util.HashMap();

    // Constructor
    protected CountryOfOriginType(java.lang.String value) {
        _value_ = value;
        _table_.put(_value_,this);
    }

    public static final java.lang.String _COO_ALWAYS_USE_DESTINATION_COUNTRY = "COO_ALWAYS_USE_DESTINATION_COUNTRY";
    public static final java.lang.String _COO_NEVER_USE_DESTINATION_COUNTRY = "COO_NEVER_USE_DESTINATION_COUNTRY";
    public static final java.lang.String _COO_ABW = "COO_ABW";
    public static final java.lang.String _COO_AFG = "COO_AFG";
    public static final java.lang.String _COO_AGO = "COO_AGO";
    public static final java.lang.String _COO_AIA = "COO_AIA";
    public static final java.lang.String _COO_ALB = "COO_ALB";
    public static final java.lang.String _COO_AND = "COO_AND";
    public static final java.lang.String _COO_ANT = "COO_ANT";
    public static final java.lang.String _COO_ARE = "COO_ARE";
    public static final java.lang.String _COO_ARG = "COO_ARG";
    public static final java.lang.String _COO_ARM = "COO_ARM";
    public static final java.lang.String _COO_ASM = "COO_ASM";
    public static final java.lang.String _COO_ATA = "COO_ATA";
    public static final java.lang.String _COO_ATF = "COO_ATF";
    public static final java.lang.String _COO_ATG = "COO_ATG";
    public static final java.lang.String _COO_AUS = "COO_AUS";
    public static final java.lang.String _COO_AUT = "COO_AUT";
    public static final java.lang.String _COO_AZE = "COO_AZE";
    public static final java.lang.String _COO_BDI = "COO_BDI";
    public static final java.lang.String _COO_BEL = "COO_BEL";
    public static final java.lang.String _COO_BEN = "COO_BEN";
    public static final java.lang.String _COO_BFA = "COO_BFA";
    public static final java.lang.String _COO_BGD = "COO_BGD";
    public static final java.lang.String _COO_BGR = "COO_BGR";
    public static final java.lang.String _COO_BHR = "COO_BHR";
    public static final java.lang.String _COO_BHS = "COO_BHS";
    public static final java.lang.String _COO_BIH = "COO_BIH";
    public static final java.lang.String _COO_BLR = "COO_BLR";
    public static final java.lang.String _COO_BLZ = "COO_BLZ";
    public static final java.lang.String _COO_BMU = "COO_BMU";
    public static final java.lang.String _COO_BOL = "COO_BOL";
    public static final java.lang.String _COO_BRA = "COO_BRA";
    public static final java.lang.String _COO_BRB = "COO_BRB";
    public static final java.lang.String _COO_BRN = "COO_BRN";
    public static final java.lang.String _COO_BTN = "COO_BTN";
    public static final java.lang.String _COO_BVT = "COO_BVT";
    public static final java.lang.String _COO_BWA = "COO_BWA";
    public static final java.lang.String _COO_CAF = "COO_CAF";
    public static final java.lang.String _COO_CAN = "COO_CAN";
    public static final java.lang.String _COO_CCK = "COO_CCK";
    public static final java.lang.String _COO_CHE = "COO_CHE";
    public static final java.lang.String _COO_CHL = "COO_CHL";
    public static final java.lang.String _COO_CHN = "COO_CHN";
    public static final java.lang.String _COO_CIV = "COO_CIV";
    public static final java.lang.String _COO_CMR = "COO_CMR";
    public static final java.lang.String _COO_COD = "COO_COD";
    public static final java.lang.String _COO_COG = "COO_COG";
    public static final java.lang.String _COO_COK = "COO_COK";
    public static final java.lang.String _COO_COL = "COO_COL";
    public static final java.lang.String _COO_COM = "COO_COM";
    public static final java.lang.String _COO_CPV = "COO_CPV";
    public static final java.lang.String _COO_CRI = "COO_CRI";
    public static final java.lang.String _COO_CUB = "COO_CUB";
    public static final java.lang.String _COO_CXR = "COO_CXR";
    public static final java.lang.String _COO_CYM = "COO_CYM";
    public static final java.lang.String _COO_CYP = "COO_CYP";
    public static final java.lang.String _COO_CZE = "COO_CZE";
    public static final java.lang.String _COO_DEU = "COO_DEU";
    public static final java.lang.String _COO_DJI = "COO_DJI";
    public static final java.lang.String _COO_DMA = "COO_DMA";
    public static final java.lang.String _COO_DNK = "COO_DNK";
    public static final java.lang.String _COO_DOM = "COO_DOM";
    public static final java.lang.String _COO_DZA = "COO_DZA";
    public static final java.lang.String _COO_ECU = "COO_ECU";
    public static final java.lang.String _COO_EGY = "COO_EGY";
    public static final java.lang.String _COO_ERI = "COO_ERI";
    public static final java.lang.String _COO_ESH = "COO_ESH";
    public static final java.lang.String _COO_ESP = "COO_ESP";
    public static final java.lang.String _COO_EST = "COO_EST";
    public static final java.lang.String _COO_ETH = "COO_ETH";
    public static final java.lang.String _COO_FIN = "COO_FIN";
    public static final java.lang.String _COO_FJI = "COO_FJI";
    public static final java.lang.String _COO_FLK = "COO_FLK";
    public static final java.lang.String _COO_FRA = "COO_FRA";
    public static final java.lang.String _COO_FRO = "COO_FRO";
    public static final java.lang.String _COO_FSM = "COO_FSM";
    public static final java.lang.String _COO_GAB = "COO_GAB";
    public static final java.lang.String _COO_GBR = "COO_GBR";
    public static final java.lang.String _COO_GEO = "COO_GEO";
    public static final java.lang.String _COO_GHA = "COO_GHA";
    public static final java.lang.String _COO_GIB = "COO_GIB";
    public static final java.lang.String _COO_GIN = "COO_GIN";
    public static final java.lang.String _COO_GLP = "COO_GLP";
    public static final java.lang.String _COO_GMB = "COO_GMB";
    public static final java.lang.String _COO_GNB = "COO_GNB";
    public static final java.lang.String _COO_GNQ = "COO_GNQ";
    public static final java.lang.String _COO_GRC = "COO_GRC";
    public static final java.lang.String _COO_GRD = "COO_GRD";
    public static final java.lang.String _COO_GRL = "COO_GRL";
    public static final java.lang.String _COO_GTM = "COO_GTM";
    public static final java.lang.String _COO_GUF = "COO_GUF";
    public static final java.lang.String _COO_GUM = "COO_GUM";
    public static final java.lang.String _COO_GUY = "COO_GUY";
    public static final java.lang.String _COO_HKG = "COO_HKG";
    public static final java.lang.String _COO_HMD = "COO_HMD";
    public static final java.lang.String _COO_HND = "COO_HND";
    public static final java.lang.String _COO_HRV = "COO_HRV";
    public static final java.lang.String _COO_HTI = "COO_HTI";
    public static final java.lang.String _COO_HUN = "COO_HUN";
    public static final java.lang.String _COO_IDN = "COO_IDN";
    public static final java.lang.String _COO_IND = "COO_IND";
    public static final java.lang.String _COO_IOT = "COO_IOT";
    public static final java.lang.String _COO_IRL = "COO_IRL";
    public static final java.lang.String _COO_IRN = "COO_IRN";
    public static final java.lang.String _COO_IRQ = "COO_IRQ";
    public static final java.lang.String _COO_ISL = "COO_ISL";
    public static final java.lang.String _COO_ISR = "COO_ISR";
    public static final java.lang.String _COO_ITA = "COO_ITA";
    public static final java.lang.String _COO_JAM = "COO_JAM";
    public static final java.lang.String _COO_JOR = "COO_JOR";
    public static final java.lang.String _COO_JPN = "COO_JPN";
    public static final java.lang.String _COO_KAZ = "COO_KAZ";
    public static final java.lang.String _COO_KEN = "COO_KEN";
    public static final java.lang.String _COO_KGZ = "COO_KGZ";
    public static final java.lang.String _COO_KHM = "COO_KHM";
    public static final java.lang.String _COO_KIR = "COO_KIR";
    public static final java.lang.String _COO_KNA = "COO_KNA";
    public static final java.lang.String _COO_KOR = "COO_KOR";
    public static final java.lang.String _COO_KWT = "COO_KWT";
    public static final java.lang.String _COO_LAO = "COO_LAO";
    public static final java.lang.String _COO_LBN = "COO_LBN";
    public static final java.lang.String _COO_LBR = "COO_LBR";
    public static final java.lang.String _COO_LBY = "COO_LBY";
    public static final java.lang.String _COO_LCA = "COO_LCA";
    public static final java.lang.String _COO_LIE = "COO_LIE";
    public static final java.lang.String _COO_LKA = "COO_LKA";
    public static final java.lang.String _COO_LSO = "COO_LSO";
    public static final java.lang.String _COO_LTU = "COO_LTU";
    public static final java.lang.String _COO_LUX = "COO_LUX";
    public static final java.lang.String _COO_LVA = "COO_LVA";
    public static final java.lang.String _COO_MAC = "COO_MAC";
    public static final java.lang.String _COO_MAR = "COO_MAR";
    public static final java.lang.String _COO_MCO = "COO_MCO";
    public static final java.lang.String _COO_MDA = "COO_MDA";
    public static final java.lang.String _COO_MDG = "COO_MDG";
    public static final java.lang.String _COO_MDV = "COO_MDV";
    public static final java.lang.String _COO_MEX = "COO_MEX";
    public static final java.lang.String _COO_MHL = "COO_MHL";
    public static final java.lang.String _COO_MKD = "COO_MKD";
    public static final java.lang.String _COO_MLI = "COO_MLI";
    public static final java.lang.String _COO_MLT = "COO_MLT";
    public static final java.lang.String _COO_MMR = "COO_MMR";
    public static final java.lang.String _COO_MNG = "COO_MNG";
    public static final java.lang.String _COO_MNP = "COO_MNP";
    public static final java.lang.String _COO_MOZ = "COO_MOZ";
    public static final java.lang.String _COO_MRT = "COO_MRT";
    public static final java.lang.String _COO_MSR = "COO_MSR";
    public static final java.lang.String _COO_MTQ = "COO_MTQ";
    public static final java.lang.String _COO_MUS = "COO_MUS";
    public static final java.lang.String _COO_MWI = "COO_MWI";
    public static final java.lang.String _COO_MYS = "COO_MYS";
    public static final java.lang.String _COO_MYT = "COO_MYT";
    public static final java.lang.String _COO_NAM = "COO_NAM";
    public static final java.lang.String _COO_NCL = "COO_NCL";
    public static final java.lang.String _COO_NER = "COO_NER";
    public static final java.lang.String _COO_NFK = "COO_NFK";
    public static final java.lang.String _COO_NGA = "COO_NGA";
    public static final java.lang.String _COO_NIC = "COO_NIC";
    public static final java.lang.String _COO_NIU = "COO_NIU";
    public static final java.lang.String _COO_NLD = "COO_NLD";
    public static final java.lang.String _COO_NOR = "COO_NOR";
    public static final java.lang.String _COO_NPL = "COO_NPL";
    public static final java.lang.String _COO_NRU = "COO_NRU";
    public static final java.lang.String _COO_NZL = "COO_NZL";
    public static final java.lang.String _COO_OMN = "COO_OMN";
    public static final java.lang.String _COO_PAK = "COO_PAK";
    public static final java.lang.String _COO_PAN = "COO_PAN";
    public static final java.lang.String _COO_PCN = "COO_PCN";
    public static final java.lang.String _COO_PER = "COO_PER";
    public static final java.lang.String _COO_PHL = "COO_PHL";
    public static final java.lang.String _COO_PLW = "COO_PLW";
    public static final java.lang.String _COO_PNG = "COO_PNG";
    public static final java.lang.String _COO_POL = "COO_POL";
    public static final java.lang.String _COO_PRI = "COO_PRI";
    public static final java.lang.String _COO_PRK = "COO_PRK";
    public static final java.lang.String _COO_PRT = "COO_PRT";
    public static final java.lang.String _COO_PRY = "COO_PRY";
    public static final java.lang.String _COO_PSE = "COO_PSE";
    public static final java.lang.String _COO_PYF = "COO_PYF";
    public static final java.lang.String _COO_QAT = "COO_QAT";
    public static final java.lang.String _COO_REU = "COO_REU";
    public static final java.lang.String _COO_ROU = "COO_ROU";
    public static final java.lang.String _COO_RUS = "COO_RUS";
    public static final java.lang.String _COO_RWA = "COO_RWA";
    public static final java.lang.String _COO_SAU = "COO_SAU";
    public static final java.lang.String _COO_SDN = "COO_SDN";
    public static final java.lang.String _COO_SEN = "COO_SEN";
    public static final java.lang.String _COO_SGP = "COO_SGP";
    public static final java.lang.String _COO_SGS = "COO_SGS";
    public static final java.lang.String _COO_SHN = "COO_SHN";
    public static final java.lang.String _COO_SJM = "COO_SJM";
    public static final java.lang.String _COO_SLB = "COO_SLB";
    public static final java.lang.String _COO_SLE = "COO_SLE";
    public static final java.lang.String _COO_SLV = "COO_SLV";
    public static final java.lang.String _COO_SMR = "COO_SMR";
    public static final java.lang.String _COO_SOM = "COO_SOM";
    public static final java.lang.String _COO_SPM = "COO_SPM";
    public static final java.lang.String _COO_STP = "COO_STP";
    public static final java.lang.String _COO_SUR = "COO_SUR";
    public static final java.lang.String _COO_SVK = "COO_SVK";
    public static final java.lang.String _COO_SVN = "COO_SVN";
    public static final java.lang.String _COO_SWE = "COO_SWE";
    public static final java.lang.String _COO_SWZ = "COO_SWZ";
    public static final java.lang.String _COO_SYC = "COO_SYC";
    public static final java.lang.String _COO_SYR = "COO_SYR";
    public static final java.lang.String _COO_TCA = "COO_TCA";
    public static final java.lang.String _COO_TCD = "COO_TCD";
    public static final java.lang.String _COO_TGO = "COO_TGO";
    public static final java.lang.String _COO_THA = "COO_THA";
    public static final java.lang.String _COO_TJK = "COO_TJK";
    public static final java.lang.String _COO_TKL = "COO_TKL";
    public static final java.lang.String _COO_TKM = "COO_TKM";
    public static final java.lang.String _COO_TLS = "COO_TLS";
    public static final java.lang.String _COO_TON = "COO_TON";
    public static final java.lang.String _COO_TTO = "COO_TTO";
    public static final java.lang.String _COO_TUN = "COO_TUN";
    public static final java.lang.String _COO_TUR = "COO_TUR";
    public static final java.lang.String _COO_TUV = "COO_TUV";
    public static final java.lang.String _COO_TWN = "COO_TWN";
    public static final java.lang.String _COO_TZA = "COO_TZA";
    public static final java.lang.String _COO_UGA = "COO_UGA";
    public static final java.lang.String _COO_UKR = "COO_UKR";
    public static final java.lang.String _COO_UMI = "COO_UMI";
    public static final java.lang.String _COO_URY = "COO_URY";
    public static final java.lang.String _COO_USA = "COO_USA";
    public static final java.lang.String _COO_UZB = "COO_UZB";
    public static final java.lang.String _COO_VAT = "COO_VAT";
    public static final java.lang.String _COO_VCT = "COO_VCT";
    public static final java.lang.String _COO_VEN = "COO_VEN";
    public static final java.lang.String _COO_VGB = "COO_VGB";
    public static final java.lang.String _COO_VIR = "COO_VIR";
    public static final java.lang.String _COO_VNM = "COO_VNM";
    public static final java.lang.String _COO_VUT = "COO_VUT";
    public static final java.lang.String _COO_WLF = "COO_WLF";
    public static final java.lang.String _COO_WSM = "COO_WSM";
    public static final java.lang.String _COO_YEM = "COO_YEM";
    public static final java.lang.String _COO_SCG = "COO_SCG";
    public static final java.lang.String _COO_ZAF = "COO_ZAF";
    public static final java.lang.String _COO_ZMB = "COO_ZMB";
    public static final java.lang.String _COO_ZWE = "COO_ZWE";
    public static final CountryOfOriginType COO_ALWAYS_USE_DESTINATION_COUNTRY = new CountryOfOriginType(_COO_ALWAYS_USE_DESTINATION_COUNTRY);
    public static final CountryOfOriginType COO_NEVER_USE_DESTINATION_COUNTRY = new CountryOfOriginType(_COO_NEVER_USE_DESTINATION_COUNTRY);
    public static final CountryOfOriginType COO_ABW = new CountryOfOriginType(_COO_ABW);
    public static final CountryOfOriginType COO_AFG = new CountryOfOriginType(_COO_AFG);
    public static final CountryOfOriginType COO_AGO = new CountryOfOriginType(_COO_AGO);
    public static final CountryOfOriginType COO_AIA = new CountryOfOriginType(_COO_AIA);
    public static final CountryOfOriginType COO_ALB = new CountryOfOriginType(_COO_ALB);
    public static final CountryOfOriginType COO_AND = new CountryOfOriginType(_COO_AND);
    public static final CountryOfOriginType COO_ANT = new CountryOfOriginType(_COO_ANT);
    public static final CountryOfOriginType COO_ARE = new CountryOfOriginType(_COO_ARE);
    public static final CountryOfOriginType COO_ARG = new CountryOfOriginType(_COO_ARG);
    public static final CountryOfOriginType COO_ARM = new CountryOfOriginType(_COO_ARM);
    public static final CountryOfOriginType COO_ASM = new CountryOfOriginType(_COO_ASM);
    public static final CountryOfOriginType COO_ATA = new CountryOfOriginType(_COO_ATA);
    public static final CountryOfOriginType COO_ATF = new CountryOfOriginType(_COO_ATF);
    public static final CountryOfOriginType COO_ATG = new CountryOfOriginType(_COO_ATG);
    public static final CountryOfOriginType COO_AUS = new CountryOfOriginType(_COO_AUS);
    public static final CountryOfOriginType COO_AUT = new CountryOfOriginType(_COO_AUT);
    public static final CountryOfOriginType COO_AZE = new CountryOfOriginType(_COO_AZE);
    public static final CountryOfOriginType COO_BDI = new CountryOfOriginType(_COO_BDI);
    public static final CountryOfOriginType COO_BEL = new CountryOfOriginType(_COO_BEL);
    public static final CountryOfOriginType COO_BEN = new CountryOfOriginType(_COO_BEN);
    public static final CountryOfOriginType COO_BFA = new CountryOfOriginType(_COO_BFA);
    public static final CountryOfOriginType COO_BGD = new CountryOfOriginType(_COO_BGD);
    public static final CountryOfOriginType COO_BGR = new CountryOfOriginType(_COO_BGR);
    public static final CountryOfOriginType COO_BHR = new CountryOfOriginType(_COO_BHR);
    public static final CountryOfOriginType COO_BHS = new CountryOfOriginType(_COO_BHS);
    public static final CountryOfOriginType COO_BIH = new CountryOfOriginType(_COO_BIH);
    public static final CountryOfOriginType COO_BLR = new CountryOfOriginType(_COO_BLR);
    public static final CountryOfOriginType COO_BLZ = new CountryOfOriginType(_COO_BLZ);
    public static final CountryOfOriginType COO_BMU = new CountryOfOriginType(_COO_BMU);
    public static final CountryOfOriginType COO_BOL = new CountryOfOriginType(_COO_BOL);
    public static final CountryOfOriginType COO_BRA = new CountryOfOriginType(_COO_BRA);
    public static final CountryOfOriginType COO_BRB = new CountryOfOriginType(_COO_BRB);
    public static final CountryOfOriginType COO_BRN = new CountryOfOriginType(_COO_BRN);
    public static final CountryOfOriginType COO_BTN = new CountryOfOriginType(_COO_BTN);
    public static final CountryOfOriginType COO_BVT = new CountryOfOriginType(_COO_BVT);
    public static final CountryOfOriginType COO_BWA = new CountryOfOriginType(_COO_BWA);
    public static final CountryOfOriginType COO_CAF = new CountryOfOriginType(_COO_CAF);
    public static final CountryOfOriginType COO_CAN = new CountryOfOriginType(_COO_CAN);
    public static final CountryOfOriginType COO_CCK = new CountryOfOriginType(_COO_CCK);
    public static final CountryOfOriginType COO_CHE = new CountryOfOriginType(_COO_CHE);
    public static final CountryOfOriginType COO_CHL = new CountryOfOriginType(_COO_CHL);
    public static final CountryOfOriginType COO_CHN = new CountryOfOriginType(_COO_CHN);
    public static final CountryOfOriginType COO_CIV = new CountryOfOriginType(_COO_CIV);
    public static final CountryOfOriginType COO_CMR = new CountryOfOriginType(_COO_CMR);
    public static final CountryOfOriginType COO_COD = new CountryOfOriginType(_COO_COD);
    public static final CountryOfOriginType COO_COG = new CountryOfOriginType(_COO_COG);
    public static final CountryOfOriginType COO_COK = new CountryOfOriginType(_COO_COK);
    public static final CountryOfOriginType COO_COL = new CountryOfOriginType(_COO_COL);
    public static final CountryOfOriginType COO_COM = new CountryOfOriginType(_COO_COM);
    public static final CountryOfOriginType COO_CPV = new CountryOfOriginType(_COO_CPV);
    public static final CountryOfOriginType COO_CRI = new CountryOfOriginType(_COO_CRI);
    public static final CountryOfOriginType COO_CUB = new CountryOfOriginType(_COO_CUB);
    public static final CountryOfOriginType COO_CXR = new CountryOfOriginType(_COO_CXR);
    public static final CountryOfOriginType COO_CYM = new CountryOfOriginType(_COO_CYM);
    public static final CountryOfOriginType COO_CYP = new CountryOfOriginType(_COO_CYP);
    public static final CountryOfOriginType COO_CZE = new CountryOfOriginType(_COO_CZE);
    public static final CountryOfOriginType COO_DEU = new CountryOfOriginType(_COO_DEU);
    public static final CountryOfOriginType COO_DJI = new CountryOfOriginType(_COO_DJI);
    public static final CountryOfOriginType COO_DMA = new CountryOfOriginType(_COO_DMA);
    public static final CountryOfOriginType COO_DNK = new CountryOfOriginType(_COO_DNK);
    public static final CountryOfOriginType COO_DOM = new CountryOfOriginType(_COO_DOM);
    public static final CountryOfOriginType COO_DZA = new CountryOfOriginType(_COO_DZA);
    public static final CountryOfOriginType COO_ECU = new CountryOfOriginType(_COO_ECU);
    public static final CountryOfOriginType COO_EGY = new CountryOfOriginType(_COO_EGY);
    public static final CountryOfOriginType COO_ERI = new CountryOfOriginType(_COO_ERI);
    public static final CountryOfOriginType COO_ESH = new CountryOfOriginType(_COO_ESH);
    public static final CountryOfOriginType COO_ESP = new CountryOfOriginType(_COO_ESP);
    public static final CountryOfOriginType COO_EST = new CountryOfOriginType(_COO_EST);
    public static final CountryOfOriginType COO_ETH = new CountryOfOriginType(_COO_ETH);
    public static final CountryOfOriginType COO_FIN = new CountryOfOriginType(_COO_FIN);
    public static final CountryOfOriginType COO_FJI = new CountryOfOriginType(_COO_FJI);
    public static final CountryOfOriginType COO_FLK = new CountryOfOriginType(_COO_FLK);
    public static final CountryOfOriginType COO_FRA = new CountryOfOriginType(_COO_FRA);
    public static final CountryOfOriginType COO_FRO = new CountryOfOriginType(_COO_FRO);
    public static final CountryOfOriginType COO_FSM = new CountryOfOriginType(_COO_FSM);
    public static final CountryOfOriginType COO_GAB = new CountryOfOriginType(_COO_GAB);
    public static final CountryOfOriginType COO_GBR = new CountryOfOriginType(_COO_GBR);
    public static final CountryOfOriginType COO_GEO = new CountryOfOriginType(_COO_GEO);
    public static final CountryOfOriginType COO_GHA = new CountryOfOriginType(_COO_GHA);
    public static final CountryOfOriginType COO_GIB = new CountryOfOriginType(_COO_GIB);
    public static final CountryOfOriginType COO_GIN = new CountryOfOriginType(_COO_GIN);
    public static final CountryOfOriginType COO_GLP = new CountryOfOriginType(_COO_GLP);
    public static final CountryOfOriginType COO_GMB = new CountryOfOriginType(_COO_GMB);
    public static final CountryOfOriginType COO_GNB = new CountryOfOriginType(_COO_GNB);
    public static final CountryOfOriginType COO_GNQ = new CountryOfOriginType(_COO_GNQ);
    public static final CountryOfOriginType COO_GRC = new CountryOfOriginType(_COO_GRC);
    public static final CountryOfOriginType COO_GRD = new CountryOfOriginType(_COO_GRD);
    public static final CountryOfOriginType COO_GRL = new CountryOfOriginType(_COO_GRL);
    public static final CountryOfOriginType COO_GTM = new CountryOfOriginType(_COO_GTM);
    public static final CountryOfOriginType COO_GUF = new CountryOfOriginType(_COO_GUF);
    public static final CountryOfOriginType COO_GUM = new CountryOfOriginType(_COO_GUM);
    public static final CountryOfOriginType COO_GUY = new CountryOfOriginType(_COO_GUY);
    public static final CountryOfOriginType COO_HKG = new CountryOfOriginType(_COO_HKG);
    public static final CountryOfOriginType COO_HMD = new CountryOfOriginType(_COO_HMD);
    public static final CountryOfOriginType COO_HND = new CountryOfOriginType(_COO_HND);
    public static final CountryOfOriginType COO_HRV = new CountryOfOriginType(_COO_HRV);
    public static final CountryOfOriginType COO_HTI = new CountryOfOriginType(_COO_HTI);
    public static final CountryOfOriginType COO_HUN = new CountryOfOriginType(_COO_HUN);
    public static final CountryOfOriginType COO_IDN = new CountryOfOriginType(_COO_IDN);
    public static final CountryOfOriginType COO_IND = new CountryOfOriginType(_COO_IND);
    public static final CountryOfOriginType COO_IOT = new CountryOfOriginType(_COO_IOT);
    public static final CountryOfOriginType COO_IRL = new CountryOfOriginType(_COO_IRL);
    public static final CountryOfOriginType COO_IRN = new CountryOfOriginType(_COO_IRN);
    public static final CountryOfOriginType COO_IRQ = new CountryOfOriginType(_COO_IRQ);
    public static final CountryOfOriginType COO_ISL = new CountryOfOriginType(_COO_ISL);
    public static final CountryOfOriginType COO_ISR = new CountryOfOriginType(_COO_ISR);
    public static final CountryOfOriginType COO_ITA = new CountryOfOriginType(_COO_ITA);
    public static final CountryOfOriginType COO_JAM = new CountryOfOriginType(_COO_JAM);
    public static final CountryOfOriginType COO_JOR = new CountryOfOriginType(_COO_JOR);
    public static final CountryOfOriginType COO_JPN = new CountryOfOriginType(_COO_JPN);
    public static final CountryOfOriginType COO_KAZ = new CountryOfOriginType(_COO_KAZ);
    public static final CountryOfOriginType COO_KEN = new CountryOfOriginType(_COO_KEN);
    public static final CountryOfOriginType COO_KGZ = new CountryOfOriginType(_COO_KGZ);
    public static final CountryOfOriginType COO_KHM = new CountryOfOriginType(_COO_KHM);
    public static final CountryOfOriginType COO_KIR = new CountryOfOriginType(_COO_KIR);
    public static final CountryOfOriginType COO_KNA = new CountryOfOriginType(_COO_KNA);
    public static final CountryOfOriginType COO_KOR = new CountryOfOriginType(_COO_KOR);
    public static final CountryOfOriginType COO_KWT = new CountryOfOriginType(_COO_KWT);
    public static final CountryOfOriginType COO_LAO = new CountryOfOriginType(_COO_LAO);
    public static final CountryOfOriginType COO_LBN = new CountryOfOriginType(_COO_LBN);
    public static final CountryOfOriginType COO_LBR = new CountryOfOriginType(_COO_LBR);
    public static final CountryOfOriginType COO_LBY = new CountryOfOriginType(_COO_LBY);
    public static final CountryOfOriginType COO_LCA = new CountryOfOriginType(_COO_LCA);
    public static final CountryOfOriginType COO_LIE = new CountryOfOriginType(_COO_LIE);
    public static final CountryOfOriginType COO_LKA = new CountryOfOriginType(_COO_LKA);
    public static final CountryOfOriginType COO_LSO = new CountryOfOriginType(_COO_LSO);
    public static final CountryOfOriginType COO_LTU = new CountryOfOriginType(_COO_LTU);
    public static final CountryOfOriginType COO_LUX = new CountryOfOriginType(_COO_LUX);
    public static final CountryOfOriginType COO_LVA = new CountryOfOriginType(_COO_LVA);
    public static final CountryOfOriginType COO_MAC = new CountryOfOriginType(_COO_MAC);
    public static final CountryOfOriginType COO_MAR = new CountryOfOriginType(_COO_MAR);
    public static final CountryOfOriginType COO_MCO = new CountryOfOriginType(_COO_MCO);
    public static final CountryOfOriginType COO_MDA = new CountryOfOriginType(_COO_MDA);
    public static final CountryOfOriginType COO_MDG = new CountryOfOriginType(_COO_MDG);
    public static final CountryOfOriginType COO_MDV = new CountryOfOriginType(_COO_MDV);
    public static final CountryOfOriginType COO_MEX = new CountryOfOriginType(_COO_MEX);
    public static final CountryOfOriginType COO_MHL = new CountryOfOriginType(_COO_MHL);
    public static final CountryOfOriginType COO_MKD = new CountryOfOriginType(_COO_MKD);
    public static final CountryOfOriginType COO_MLI = new CountryOfOriginType(_COO_MLI);
    public static final CountryOfOriginType COO_MLT = new CountryOfOriginType(_COO_MLT);
    public static final CountryOfOriginType COO_MMR = new CountryOfOriginType(_COO_MMR);
    public static final CountryOfOriginType COO_MNG = new CountryOfOriginType(_COO_MNG);
    public static final CountryOfOriginType COO_MNP = new CountryOfOriginType(_COO_MNP);
    public static final CountryOfOriginType COO_MOZ = new CountryOfOriginType(_COO_MOZ);
    public static final CountryOfOriginType COO_MRT = new CountryOfOriginType(_COO_MRT);
    public static final CountryOfOriginType COO_MSR = new CountryOfOriginType(_COO_MSR);
    public static final CountryOfOriginType COO_MTQ = new CountryOfOriginType(_COO_MTQ);
    public static final CountryOfOriginType COO_MUS = new CountryOfOriginType(_COO_MUS);
    public static final CountryOfOriginType COO_MWI = new CountryOfOriginType(_COO_MWI);
    public static final CountryOfOriginType COO_MYS = new CountryOfOriginType(_COO_MYS);
    public static final CountryOfOriginType COO_MYT = new CountryOfOriginType(_COO_MYT);
    public static final CountryOfOriginType COO_NAM = new CountryOfOriginType(_COO_NAM);
    public static final CountryOfOriginType COO_NCL = new CountryOfOriginType(_COO_NCL);
    public static final CountryOfOriginType COO_NER = new CountryOfOriginType(_COO_NER);
    public static final CountryOfOriginType COO_NFK = new CountryOfOriginType(_COO_NFK);
    public static final CountryOfOriginType COO_NGA = new CountryOfOriginType(_COO_NGA);
    public static final CountryOfOriginType COO_NIC = new CountryOfOriginType(_COO_NIC);
    public static final CountryOfOriginType COO_NIU = new CountryOfOriginType(_COO_NIU);
    public static final CountryOfOriginType COO_NLD = new CountryOfOriginType(_COO_NLD);
    public static final CountryOfOriginType COO_NOR = new CountryOfOriginType(_COO_NOR);
    public static final CountryOfOriginType COO_NPL = new CountryOfOriginType(_COO_NPL);
    public static final CountryOfOriginType COO_NRU = new CountryOfOriginType(_COO_NRU);
    public static final CountryOfOriginType COO_NZL = new CountryOfOriginType(_COO_NZL);
    public static final CountryOfOriginType COO_OMN = new CountryOfOriginType(_COO_OMN);
    public static final CountryOfOriginType COO_PAK = new CountryOfOriginType(_COO_PAK);
    public static final CountryOfOriginType COO_PAN = new CountryOfOriginType(_COO_PAN);
    public static final CountryOfOriginType COO_PCN = new CountryOfOriginType(_COO_PCN);
    public static final CountryOfOriginType COO_PER = new CountryOfOriginType(_COO_PER);
    public static final CountryOfOriginType COO_PHL = new CountryOfOriginType(_COO_PHL);
    public static final CountryOfOriginType COO_PLW = new CountryOfOriginType(_COO_PLW);
    public static final CountryOfOriginType COO_PNG = new CountryOfOriginType(_COO_PNG);
    public static final CountryOfOriginType COO_POL = new CountryOfOriginType(_COO_POL);
    public static final CountryOfOriginType COO_PRI = new CountryOfOriginType(_COO_PRI);
    public static final CountryOfOriginType COO_PRK = new CountryOfOriginType(_COO_PRK);
    public static final CountryOfOriginType COO_PRT = new CountryOfOriginType(_COO_PRT);
    public static final CountryOfOriginType COO_PRY = new CountryOfOriginType(_COO_PRY);
    public static final CountryOfOriginType COO_PSE = new CountryOfOriginType(_COO_PSE);
    public static final CountryOfOriginType COO_PYF = new CountryOfOriginType(_COO_PYF);
    public static final CountryOfOriginType COO_QAT = new CountryOfOriginType(_COO_QAT);
    public static final CountryOfOriginType COO_REU = new CountryOfOriginType(_COO_REU);
    public static final CountryOfOriginType COO_ROU = new CountryOfOriginType(_COO_ROU);
    public static final CountryOfOriginType COO_RUS = new CountryOfOriginType(_COO_RUS);
    public static final CountryOfOriginType COO_RWA = new CountryOfOriginType(_COO_RWA);
    public static final CountryOfOriginType COO_SAU = new CountryOfOriginType(_COO_SAU);
    public static final CountryOfOriginType COO_SDN = new CountryOfOriginType(_COO_SDN);
    public static final CountryOfOriginType COO_SEN = new CountryOfOriginType(_COO_SEN);
    public static final CountryOfOriginType COO_SGP = new CountryOfOriginType(_COO_SGP);
    public static final CountryOfOriginType COO_SGS = new CountryOfOriginType(_COO_SGS);
    public static final CountryOfOriginType COO_SHN = new CountryOfOriginType(_COO_SHN);
    public static final CountryOfOriginType COO_SJM = new CountryOfOriginType(_COO_SJM);
    public static final CountryOfOriginType COO_SLB = new CountryOfOriginType(_COO_SLB);
    public static final CountryOfOriginType COO_SLE = new CountryOfOriginType(_COO_SLE);
    public static final CountryOfOriginType COO_SLV = new CountryOfOriginType(_COO_SLV);
    public static final CountryOfOriginType COO_SMR = new CountryOfOriginType(_COO_SMR);
    public static final CountryOfOriginType COO_SOM = new CountryOfOriginType(_COO_SOM);
    public static final CountryOfOriginType COO_SPM = new CountryOfOriginType(_COO_SPM);
    public static final CountryOfOriginType COO_STP = new CountryOfOriginType(_COO_STP);
    public static final CountryOfOriginType COO_SUR = new CountryOfOriginType(_COO_SUR);
    public static final CountryOfOriginType COO_SVK = new CountryOfOriginType(_COO_SVK);
    public static final CountryOfOriginType COO_SVN = new CountryOfOriginType(_COO_SVN);
    public static final CountryOfOriginType COO_SWE = new CountryOfOriginType(_COO_SWE);
    public static final CountryOfOriginType COO_SWZ = new CountryOfOriginType(_COO_SWZ);
    public static final CountryOfOriginType COO_SYC = new CountryOfOriginType(_COO_SYC);
    public static final CountryOfOriginType COO_SYR = new CountryOfOriginType(_COO_SYR);
    public static final CountryOfOriginType COO_TCA = new CountryOfOriginType(_COO_TCA);
    public static final CountryOfOriginType COO_TCD = new CountryOfOriginType(_COO_TCD);
    public static final CountryOfOriginType COO_TGO = new CountryOfOriginType(_COO_TGO);
    public static final CountryOfOriginType COO_THA = new CountryOfOriginType(_COO_THA);
    public static final CountryOfOriginType COO_TJK = new CountryOfOriginType(_COO_TJK);
    public static final CountryOfOriginType COO_TKL = new CountryOfOriginType(_COO_TKL);
    public static final CountryOfOriginType COO_TKM = new CountryOfOriginType(_COO_TKM);
    public static final CountryOfOriginType COO_TLS = new CountryOfOriginType(_COO_TLS);
    public static final CountryOfOriginType COO_TON = new CountryOfOriginType(_COO_TON);
    public static final CountryOfOriginType COO_TTO = new CountryOfOriginType(_COO_TTO);
    public static final CountryOfOriginType COO_TUN = new CountryOfOriginType(_COO_TUN);
    public static final CountryOfOriginType COO_TUR = new CountryOfOriginType(_COO_TUR);
    public static final CountryOfOriginType COO_TUV = new CountryOfOriginType(_COO_TUV);
    public static final CountryOfOriginType COO_TWN = new CountryOfOriginType(_COO_TWN);
    public static final CountryOfOriginType COO_TZA = new CountryOfOriginType(_COO_TZA);
    public static final CountryOfOriginType COO_UGA = new CountryOfOriginType(_COO_UGA);
    public static final CountryOfOriginType COO_UKR = new CountryOfOriginType(_COO_UKR);
    public static final CountryOfOriginType COO_UMI = new CountryOfOriginType(_COO_UMI);
    public static final CountryOfOriginType COO_URY = new CountryOfOriginType(_COO_URY);
    public static final CountryOfOriginType COO_USA = new CountryOfOriginType(_COO_USA);
    public static final CountryOfOriginType COO_UZB = new CountryOfOriginType(_COO_UZB);
    public static final CountryOfOriginType COO_VAT = new CountryOfOriginType(_COO_VAT);
    public static final CountryOfOriginType COO_VCT = new CountryOfOriginType(_COO_VCT);
    public static final CountryOfOriginType COO_VEN = new CountryOfOriginType(_COO_VEN);
    public static final CountryOfOriginType COO_VGB = new CountryOfOriginType(_COO_VGB);
    public static final CountryOfOriginType COO_VIR = new CountryOfOriginType(_COO_VIR);
    public static final CountryOfOriginType COO_VNM = new CountryOfOriginType(_COO_VNM);
    public static final CountryOfOriginType COO_VUT = new CountryOfOriginType(_COO_VUT);
    public static final CountryOfOriginType COO_WLF = new CountryOfOriginType(_COO_WLF);
    public static final CountryOfOriginType COO_WSM = new CountryOfOriginType(_COO_WSM);
    public static final CountryOfOriginType COO_YEM = new CountryOfOriginType(_COO_YEM);
    public static final CountryOfOriginType COO_SCG = new CountryOfOriginType(_COO_SCG);
    public static final CountryOfOriginType COO_ZAF = new CountryOfOriginType(_COO_ZAF);
    public static final CountryOfOriginType COO_ZMB = new CountryOfOriginType(_COO_ZMB);
    public static final CountryOfOriginType COO_ZWE = new CountryOfOriginType(_COO_ZWE);
    public java.lang.String getValue() { return _value_;}
    public static CountryOfOriginType fromValue(java.lang.String value)
          throws java.lang.IllegalArgumentException {
        CountryOfOriginType enumeration = (CountryOfOriginType)
            _table_.get(value);
        if (enumeration==null) throw new java.lang.IllegalArgumentException();
        return enumeration;
    }
    public static CountryOfOriginType fromString(java.lang.String value)
          throws java.lang.IllegalArgumentException {
        return fromValue(value);
    }
    public boolean equals(java.lang.Object obj) {return (obj == this);}
    public int hashCode() { return toString().hashCode();}
    public java.lang.String toString() { return _value_;}
    public java.lang.Object readResolve() throws java.io.ObjectStreamException { return fromValue(_value_);}
    public static org.apache.axis.encoding.Serializer getSerializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new org.apache.axis.encoding.ser.EnumSerializer(
            _javaType, _xmlType);
    }
    public static org.apache.axis.encoding.Deserializer getDeserializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new org.apache.axis.encoding.ser.EnumDeserializer(
            _javaType, _xmlType);
    }
    // Type metadata
    private static org.apache.axis.description.TypeDesc typeDesc =
        new org.apache.axis.description.TypeDesc(CountryOfOriginType.class);

    static {
        typeDesc.setXmlType(new javax.xml.namespace.QName("http://validator2.AddressDoctor.com/addInteractive/Interactive", "CountryOfOriginType"));
    }
    /**
     * Return type metadata object
     */
    public static org.apache.axis.description.TypeDesc getTypeDesc() {
        return typeDesc;
    }

}
