package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public class DescribeDataCategoryGroupStructures_element implements com.sforce.ws.bind.XMLizable , IDescribeDataCategoryGroupStructures_element{

    /**
     * Constructor
     */
    public DescribeDataCategoryGroupStructures_element() {}

    /**
     * element : pairs of type {urn:partner.soap.sforce.com}DataCategoryGroupSobjectTypePair
     * java type: com.sforce.soap.partner.DataCategoryGroupSobjectTypePair[]
     */
    private static final com.sforce.ws.bind.TypeInfo pairs__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","pairs","urn:partner.soap.sforce.com","DataCategoryGroupSobjectTypePair",0,100,true);

    private boolean pairs__is_set = false;

    private com.sforce.soap.partner.DataCategoryGroupSobjectTypePair[] pairs = new com.sforce.soap.partner.DataCategoryGroupSobjectTypePair[0];

    @Override
    public com.sforce.soap.partner.DataCategoryGroupSobjectTypePair[] getPairs() {
      return pairs;
    }

    @Override
    public void setPairs(com.sforce.soap.partner.IDataCategoryGroupSobjectTypePair[] pairs) {
      this.pairs = castArray(com.sforce.soap.partner.DataCategoryGroupSobjectTypePair.class, pairs);
      pairs__is_set = true;
    }

    protected void setPairs(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, pairs__typeInfo)) {
        setPairs((com.sforce.soap.partner.DataCategoryGroupSobjectTypePair[])__typeMapper.readObject(__in, pairs__typeInfo, com.sforce.soap.partner.DataCategoryGroupSobjectTypePair[].class));
      }
    }

    /**
     * element : topCategoriesOnly of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private static final com.sforce.ws.bind.TypeInfo topCategoriesOnly__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","topCategoriesOnly","http://www.w3.org/2001/XMLSchema","boolean",1,1,true);

    private boolean topCategoriesOnly__is_set = false;

    private boolean topCategoriesOnly;

    @Override
    public boolean getTopCategoriesOnly() {
      return topCategoriesOnly;
    }

    @Override
    public boolean isTopCategoriesOnly() {
      return topCategoriesOnly;
    }

    @Override
    public void setTopCategoriesOnly(boolean topCategoriesOnly) {
      this.topCategoriesOnly = topCategoriesOnly;
      topCategoriesOnly__is_set = true;
    }

    protected void setTopCategoriesOnly(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, topCategoriesOnly__typeInfo)) {
        setTopCategoriesOnly(__typeMapper.readBoolean(__in, topCategoriesOnly__typeInfo, boolean.class));
      }
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       __typeMapper.writeObject(__out, pairs__typeInfo, pairs, pairs__is_set);
       __typeMapper.writeBoolean(__out, topCategoriesOnly__typeInfo, topCategoriesOnly, topCategoriesOnly__is_set);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        setPairs(__in, __typeMapper);
        setTopCategoriesOnly(__in, __typeMapper);
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[DescribeDataCategoryGroupStructures_element ");
      sb.append(" pairs='").append(com.sforce.ws.util.Verbose.toString(pairs)).append("'\n");
      sb.append(" topCategoriesOnly='").append(com.sforce.ws.util.Verbose.toString(topCategoriesOnly)).append("'\n");
      sb.append("]\n");
      return sb.toString();
    }

    @SuppressWarnings("unchecked")
    private <T,U> T[] castArray(Class<T> clazz, U[] array) {
        if (array == null) {
            return null;
        }
        T[] retVal = (T[]) java.lang.reflect.Array.newInstance(clazz, array.length);
        for (int i=0; i < array.length; i++) {
            retVal[i] = (T)array[i];
        }

        return retVal;
	}
}
