package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public class DescribeSoqlListViewResult implements com.sforce.ws.bind.XMLizable , IDescribeSoqlListViewResult{

    /**
     * Constructor
     */
    public DescribeSoqlListViewResult() {}

    /**
     * element : describeSoqlListViews of type {urn:partner.soap.sforce.com}DescribeSoqlListView
     * java type: com.sforce.soap.partner.DescribeSoqlListView[]
     */
    private static final com.sforce.ws.bind.TypeInfo describeSoqlListViews__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","describeSoqlListViews","urn:partner.soap.sforce.com","DescribeSoqlListView",1,-1,true);

    private boolean describeSoqlListViews__is_set = false;

    private com.sforce.soap.partner.DescribeSoqlListView[] describeSoqlListViews = new com.sforce.soap.partner.DescribeSoqlListView[0];

    @Override
    public com.sforce.soap.partner.DescribeSoqlListView[] getDescribeSoqlListViews() {
      return describeSoqlListViews;
    }

    @Override
    public void setDescribeSoqlListViews(com.sforce.soap.partner.IDescribeSoqlListView[] describeSoqlListViews) {
      this.describeSoqlListViews = castArray(com.sforce.soap.partner.DescribeSoqlListView.class, describeSoqlListViews);
      describeSoqlListViews__is_set = true;
    }

    protected void setDescribeSoqlListViews(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, describeSoqlListViews__typeInfo)) {
        setDescribeSoqlListViews((com.sforce.soap.partner.DescribeSoqlListView[])__typeMapper.readObject(__in, describeSoqlListViews__typeInfo, com.sforce.soap.partner.DescribeSoqlListView[].class));
      }
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       __typeMapper.writeObject(__out, describeSoqlListViews__typeInfo, describeSoqlListViews, describeSoqlListViews__is_set);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        setDescribeSoqlListViews(__in, __typeMapper);
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[DescribeSoqlListViewResult ");
      sb.append(" describeSoqlListViews='").append(com.sforce.ws.util.Verbose.toString(describeSoqlListViews)).append("'\n");
      sb.append("]\n");
      return sb.toString();
    }

    @SuppressWarnings("unchecked")
    private <T,U> T[] castArray(Class<T> clazz, U[] array) {
        if (array == null) {
            return null;
        }
        T[] retVal = (T[]) java.lang.reflect.Array.newInstance(clazz, array.length);
        for (int i=0; i < array.length; i++) {
            retVal[i] = (T)array[i];
        }

        return retVal;
	}
}
