package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public class DescribeAppMenuResult implements com.sforce.ws.bind.XMLizable , IDescribeAppMenuResult{

    /**
     * Constructor
     */
    public DescribeAppMenuResult() {}

    /**
     * element : appMenuItems of type {urn:partner.soap.sforce.com}DescribeAppMenuItem
     * java type: com.sforce.soap.partner.DescribeAppMenuItem[]
     */
    private static final com.sforce.ws.bind.TypeInfo appMenuItems__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","appMenuItems","urn:partner.soap.sforce.com","DescribeAppMenuItem",0,-1,true);

    private boolean appMenuItems__is_set = false;

    private com.sforce.soap.partner.DescribeAppMenuItem[] appMenuItems = new com.sforce.soap.partner.DescribeAppMenuItem[0];

    @Override
    public com.sforce.soap.partner.DescribeAppMenuItem[] getAppMenuItems() {
      return appMenuItems;
    }

    @Override
    public void setAppMenuItems(com.sforce.soap.partner.IDescribeAppMenuItem[] appMenuItems) {
      this.appMenuItems = castArray(com.sforce.soap.partner.DescribeAppMenuItem.class, appMenuItems);
      appMenuItems__is_set = true;
    }

    protected void setAppMenuItems(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, appMenuItems__typeInfo)) {
        setAppMenuItems((com.sforce.soap.partner.DescribeAppMenuItem[])__typeMapper.readObject(__in, appMenuItems__typeInfo, com.sforce.soap.partner.DescribeAppMenuItem[].class));
      }
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       __typeMapper.writeObject(__out, appMenuItems__typeInfo, appMenuItems, appMenuItems__is_set);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        setAppMenuItems(__in, __typeMapper);
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[DescribeAppMenuResult ");
      sb.append(" appMenuItems='").append(com.sforce.ws.util.Verbose.toString(appMenuItems)).append("'\n");
      sb.append("]\n");
      return sb.toString();
    }

    @SuppressWarnings("unchecked")
    private <T,U> T[] castArray(Class<T> clazz, U[] array) {
        if (array == null) {
            return null;
        }
        T[] retVal = (T[]) java.lang.reflect.Array.newInstance(clazz, array.length);
        for (int i=0; i < array.length; i++) {
            retVal[i] = (T)array[i];
        }

        return retVal;
	}
}
