package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public class DescribeSoqlListViews_element implements com.sforce.ws.bind.XMLizable , IDescribeSoqlListViews_element{

    /**
     * Constructor
     */
    public DescribeSoqlListViews_element() {}

    /**
     * element : request of type {urn:partner.soap.sforce.com}DescribeSoqlListViewsRequest
     * java type: com.sforce.soap.partner.DescribeSoqlListViewsRequest
     */
    private static final com.sforce.ws.bind.TypeInfo request__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","request","urn:partner.soap.sforce.com","DescribeSoqlListViewsRequest",1,1,true);

    private boolean request__is_set = false;

    private com.sforce.soap.partner.DescribeSoqlListViewsRequest request;

    @Override
    public com.sforce.soap.partner.DescribeSoqlListViewsRequest getRequest() {
      return request;
    }

    @Override
    public void setRequest(com.sforce.soap.partner.IDescribeSoqlListViewsRequest request) {
      this.request = (com.sforce.soap.partner.DescribeSoqlListViewsRequest)request;
      request__is_set = true;
    }

    protected void setRequest(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, request__typeInfo)) {
        setRequest((com.sforce.soap.partner.DescribeSoqlListViewsRequest)__typeMapper.readObject(__in, request__typeInfo, com.sforce.soap.partner.DescribeSoqlListViewsRequest.class));
      }
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       __typeMapper.writeObject(__out, request__typeInfo, request, request__is_set);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        setRequest(__in, __typeMapper);
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[DescribeSoqlListViews_element ");
      sb.append(" request='").append(com.sforce.ws.util.Verbose.toString(request)).append("'\n");
      sb.append("]\n");
      return sb.toString();
    }

}
