package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public class DescribeRelatedContentItem implements com.sforce.ws.bind.XMLizable , IDescribeRelatedContentItem{

    /**
     * Constructor
     */
    public DescribeRelatedContentItem() {}

    /**
     * element : describeLayoutItem of type {urn:partner.soap.sforce.com}DescribeLayoutItem
     * java type: com.sforce.soap.partner.DescribeLayoutItem
     */
    private static final com.sforce.ws.bind.TypeInfo describeLayoutItem__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","describeLayoutItem","urn:partner.soap.sforce.com","DescribeLayoutItem",1,1,true);

    private boolean describeLayoutItem__is_set = false;

    private com.sforce.soap.partner.DescribeLayoutItem describeLayoutItem;

    @Override
    public com.sforce.soap.partner.DescribeLayoutItem getDescribeLayoutItem() {
      return describeLayoutItem;
    }

    @Override
    public void setDescribeLayoutItem(com.sforce.soap.partner.IDescribeLayoutItem describeLayoutItem) {
      this.describeLayoutItem = (com.sforce.soap.partner.DescribeLayoutItem)describeLayoutItem;
      describeLayoutItem__is_set = true;
    }

    protected void setDescribeLayoutItem(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, describeLayoutItem__typeInfo)) {
        setDescribeLayoutItem((com.sforce.soap.partner.DescribeLayoutItem)__typeMapper.readObject(__in, describeLayoutItem__typeInfo, com.sforce.soap.partner.DescribeLayoutItem.class));
      }
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       __typeMapper.writeObject(__out, describeLayoutItem__typeInfo, describeLayoutItem, describeLayoutItem__is_set);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        setDescribeLayoutItem(__in, __typeMapper);
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[DescribeRelatedContentItem ");
      sb.append(" describeLayoutItem='").append(com.sforce.ws.util.Verbose.toString(describeLayoutItem)).append("'\n");
      sb.append("]\n");
      return sb.toString();
    }

}
