package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public class ExecuteListViewRequest implements com.sforce.ws.bind.XMLizable , IExecuteListViewRequest{

    /**
     * Constructor
     */
    public ExecuteListViewRequest() {}

    /**
     * element : developerNameOrId of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo developerNameOrId__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","developerNameOrId","http://www.w3.org/2001/XMLSchema","string",1,1,true);

    private boolean developerNameOrId__is_set = false;

    private java.lang.String developerNameOrId;

    @Override
    public java.lang.String getDeveloperNameOrId() {
      return developerNameOrId;
    }

    @Override
    public void setDeveloperNameOrId(java.lang.String developerNameOrId) {
      this.developerNameOrId = developerNameOrId;
      developerNameOrId__is_set = true;
    }

    protected void setDeveloperNameOrId(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, developerNameOrId__typeInfo)) {
        setDeveloperNameOrId(__typeMapper.readString(__in, developerNameOrId__typeInfo, java.lang.String.class));
      }
    }

    /**
     * element : limit of type {http://www.w3.org/2001/XMLSchema}int
     * java type: java.lang.Integer
     */
    private static final com.sforce.ws.bind.TypeInfo limit__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","limit","http://www.w3.org/2001/XMLSchema","int",1,1,true);

    private boolean limit__is_set = false;

    private java.lang.Integer limit;

    @Override
    public java.lang.Integer getLimit() {
      return limit;
    }

    @Override
    public void setLimit(java.lang.Integer limit) {
      this.limit = limit;
      limit__is_set = true;
    }

    protected void setLimit(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, limit__typeInfo)) {
        setLimit((java.lang.Integer)__typeMapper.readObject(__in, limit__typeInfo, java.lang.Integer.class));
      }
    }

    /**
     * element : offset of type {http://www.w3.org/2001/XMLSchema}int
     * java type: java.lang.Integer
     */
    private static final com.sforce.ws.bind.TypeInfo offset__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","offset","http://www.w3.org/2001/XMLSchema","int",1,1,true);

    private boolean offset__is_set = false;

    private java.lang.Integer offset;

    @Override
    public java.lang.Integer getOffset() {
      return offset;
    }

    @Override
    public void setOffset(java.lang.Integer offset) {
      this.offset = offset;
      offset__is_set = true;
    }

    protected void setOffset(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, offset__typeInfo)) {
        setOffset((java.lang.Integer)__typeMapper.readObject(__in, offset__typeInfo, java.lang.Integer.class));
      }
    }

    /**
     * element : orderBy of type {urn:partner.soap.sforce.com}ListViewOrderBy
     * java type: com.sforce.soap.partner.ListViewOrderBy[]
     */
    private static final com.sforce.ws.bind.TypeInfo orderBy__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","orderBy","urn:partner.soap.sforce.com","ListViewOrderBy",1,-1,true);

    private boolean orderBy__is_set = false;

    private com.sforce.soap.partner.ListViewOrderBy[] orderBy = new com.sforce.soap.partner.ListViewOrderBy[0];

    @Override
    public com.sforce.soap.partner.ListViewOrderBy[] getOrderBy() {
      return orderBy;
    }

    @Override
    public void setOrderBy(com.sforce.soap.partner.IListViewOrderBy[] orderBy) {
      this.orderBy = castArray(com.sforce.soap.partner.ListViewOrderBy.class, orderBy);
      orderBy__is_set = true;
    }

    protected void setOrderBy(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, orderBy__typeInfo)) {
        setOrderBy((com.sforce.soap.partner.ListViewOrderBy[])__typeMapper.readObject(__in, orderBy__typeInfo, com.sforce.soap.partner.ListViewOrderBy[].class));
      }
    }

    /**
     * element : sobjectType of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo sobjectType__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","sobjectType","http://www.w3.org/2001/XMLSchema","string",1,1,true);

    private boolean sobjectType__is_set = false;

    private java.lang.String sobjectType;

    @Override
    public java.lang.String getSobjectType() {
      return sobjectType;
    }

    @Override
    public void setSobjectType(java.lang.String sobjectType) {
      this.sobjectType = sobjectType;
      sobjectType__is_set = true;
    }

    protected void setSobjectType(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, sobjectType__typeInfo)) {
        setSobjectType(__typeMapper.readString(__in, sobjectType__typeInfo, java.lang.String.class));
      }
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       __typeMapper.writeString(__out, developerNameOrId__typeInfo, developerNameOrId, developerNameOrId__is_set);
       __typeMapper.writeObject(__out, limit__typeInfo, limit, limit__is_set);
       __typeMapper.writeObject(__out, offset__typeInfo, offset, offset__is_set);
       __typeMapper.writeObject(__out, orderBy__typeInfo, orderBy, orderBy__is_set);
       __typeMapper.writeString(__out, sobjectType__typeInfo, sobjectType, sobjectType__is_set);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        setDeveloperNameOrId(__in, __typeMapper);
        setLimit(__in, __typeMapper);
        setOffset(__in, __typeMapper);
        setOrderBy(__in, __typeMapper);
        setSobjectType(__in, __typeMapper);
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[ExecuteListViewRequest ");
      sb.append(" developerNameOrId='").append(com.sforce.ws.util.Verbose.toString(developerNameOrId)).append("'\n");
      sb.append(" limit='").append(com.sforce.ws.util.Verbose.toString(limit)).append("'\n");
      sb.append(" offset='").append(com.sforce.ws.util.Verbose.toString(offset)).append("'\n");
      sb.append(" orderBy='").append(com.sforce.ws.util.Verbose.toString(orderBy)).append("'\n");
      sb.append(" sobjectType='").append(com.sforce.ws.util.Verbose.toString(sobjectType)).append("'\n");
      sb.append("]\n");
      return sb.toString();
    }

    @SuppressWarnings("unchecked")
    private <T,U> T[] castArray(Class<T> clazz, U[] array) {
        if (array == null) {
            return null;
        }
        T[] retVal = (T[]) java.lang.reflect.Array.newInstance(clazz, array.length);
        for (int i=0; i < array.length; i++) {
            retVal[i] = (T)array[i];
        }

        return retVal;
	}
}
