package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IAssignmentRuleHeader_element  {

      /**
       * element : assignmentRuleId of type {urn:partner.soap.sforce.com}ID
       * java type: java.lang.String
       */

      public java.lang.String getAssignmentRuleId();

      public void setAssignmentRuleId(java.lang.String assignmentRuleId);

      /**
       * element : useDefaultRule of type {http://www.w3.org/2001/XMLSchema}boolean
       * java type: java.lang.Boolean
       */

      public java.lang.Boolean getUseDefaultRule();

      public void setUseDefaultRule(java.lang.Boolean useDefaultRule);


}
