package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IConvertLeadResponse_element  {

      /**
       * element : result of type {urn:partner.soap.sforce.com}LeadConvertResult
       * java type: com.sforce.soap.partner.LeadConvertResult[]
       */

      public com.sforce.soap.partner.ILeadConvertResult[] getResult();

      public void setResult(com.sforce.soap.partner.ILeadConvertResult[] result);


}
