package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface ICreateResponse_element  {

      /**
       * element : result of type {urn:partner.soap.sforce.com}SaveResult
       * java type: com.sforce.soap.partner.SaveResult[]
       */

      public com.sforce.soap.partner.ISaveResult[] getResult();

      public void setResult(com.sforce.soap.partner.ISaveResult[] result);


}
