package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface ICustomLinkComponent extends com.sforce.soap.partner.IDescribeLayoutComponent {

      /**
       * element : customLink of type {urn:partner.soap.sforce.com}DescribeLayoutButton
       * java type: com.sforce.soap.partner.DescribeLayoutButton
       */

      public com.sforce.soap.partner.IDescribeLayoutButton getCustomLink();

      public void setCustomLink(com.sforce.soap.partner.IDescribeLayoutButton customLink);


}
