package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IDataCategoryGroupSobjectTypePair  {

      /**
       * element : dataCategoryGroupName of type {http://www.w3.org/2001/XMLSchema}string
       * java type: java.lang.String
       */

      public java.lang.String getDataCategoryGroupName();

      public void setDataCategoryGroupName(java.lang.String dataCategoryGroupName);

      /**
       * element : sobject of type {http://www.w3.org/2001/XMLSchema}string
       * java type: java.lang.String
       */

      public java.lang.String getSobject();

      public void setSobject(java.lang.String sobject);


}
