package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IDebuggingInfo_element  {

      /**
       * element : debugLog of type {http://www.w3.org/2001/XMLSchema}string
       * java type: java.lang.String
       */

      public java.lang.String getDebugLog();

      public void setDebugLog(java.lang.String debugLog);


}
