package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IDescribeTabsResponse_element  {

      /**
       * element : result of type {urn:partner.soap.sforce.com}DescribeTabSetResult
       * java type: com.sforce.soap.partner.DescribeTabSetResult[]
       */

      public com.sforce.soap.partner.IDescribeTabSetResult[] getResult();

      public void setResult(com.sforce.soap.partner.IDescribeTabSetResult[] result);


}
