package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IDescribeSObjectResponse_element  {

      /**
       * element : result of type {urn:partner.soap.sforce.com}DescribeSObjectResult
       * java type: com.sforce.soap.partner.DescribeSObjectResult
       */

      public com.sforce.soap.partner.IDescribeSObjectResult getResult();

      public void setResult(com.sforce.soap.partner.IDescribeSObjectResult result);


}
