package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IDescribeGlobalThemeResponse_element  {

      /**
       * element : result of type {urn:partner.soap.sforce.com}DescribeGlobalTheme
       * java type: com.sforce.soap.partner.DescribeGlobalTheme
       */

      public com.sforce.soap.partner.IDescribeGlobalTheme getResult();

      public void setResult(com.sforce.soap.partner.IDescribeGlobalTheme result);


}
