package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IDescribeLayoutButton  {

      /**
       * element : behavior of type {urn:partner.soap.sforce.com}WebLinkWindowType
       * java type: com.sforce.soap.partner.WebLinkWindowType
       */

      public com.sforce.soap.partner.WebLinkWindowType getBehavior();

      public void setBehavior(com.sforce.soap.partner.WebLinkWindowType behavior);

      /**
       * element : colors of type {urn:partner.soap.sforce.com}DescribeColor
       * java type: com.sforce.soap.partner.DescribeColor[]
       */

      public com.sforce.soap.partner.IDescribeColor[] getColors();

      public void setColors(com.sforce.soap.partner.IDescribeColor[] colors);

      /**
       * element : content of type {http://www.w3.org/2001/XMLSchema}string
       * java type: java.lang.String
       */

      public java.lang.String getContent();

      public void setContent(java.lang.String content);

      /**
       * element : contentSource of type {urn:partner.soap.sforce.com}WebLinkType
       * java type: com.sforce.soap.partner.WebLinkType
       */

      public com.sforce.soap.partner.WebLinkType getContentSource();

      public void setContentSource(com.sforce.soap.partner.WebLinkType contentSource);

      /**
       * element : custom of type {http://www.w3.org/2001/XMLSchema}boolean
       * java type: boolean
       */

      public boolean getCustom();

      public boolean isCustom();

      public void setCustom(boolean custom);

      /**
       * element : encoding of type {http://www.w3.org/2001/XMLSchema}string
       * java type: java.lang.String
       */

      public java.lang.String getEncoding();

      public void setEncoding(java.lang.String encoding);

      /**
       * element : height of type {http://www.w3.org/2001/XMLSchema}int
       * java type: java.lang.Integer
       */

      public java.lang.Integer getHeight();

      public void setHeight(java.lang.Integer height);

      /**
       * element : icons of type {urn:partner.soap.sforce.com}DescribeIcon
       * java type: com.sforce.soap.partner.DescribeIcon[]
       */

      public com.sforce.soap.partner.IDescribeIcon[] getIcons();

      public void setIcons(com.sforce.soap.partner.IDescribeIcon[] icons);

      /**
       * element : label of type {http://www.w3.org/2001/XMLSchema}string
       * java type: java.lang.String
       */

      public java.lang.String getLabel();

      public void setLabel(java.lang.String label);

      /**
       * element : menubar of type {http://www.w3.org/2001/XMLSchema}boolean
       * java type: java.lang.Boolean
       */

      public java.lang.Boolean getMenubar();

      public void setMenubar(java.lang.Boolean menubar);

      /**
       * element : name of type {http://www.w3.org/2001/XMLSchema}string
       * java type: java.lang.String
       */

      public java.lang.String getName();

      public void setName(java.lang.String name);

      /**
       * element : overridden of type {http://www.w3.org/2001/XMLSchema}boolean
       * java type: boolean
       */

      public boolean getOverridden();

      public boolean isOverridden();

      public void setOverridden(boolean overridden);

      /**
       * element : resizeable of type {http://www.w3.org/2001/XMLSchema}boolean
       * java type: java.lang.Boolean
       */

      public java.lang.Boolean getResizeable();

      public void setResizeable(java.lang.Boolean resizeable);

      /**
       * element : scrollbars of type {http://www.w3.org/2001/XMLSchema}boolean
       * java type: java.lang.Boolean
       */

      public java.lang.Boolean getScrollbars();

      public void setScrollbars(java.lang.Boolean scrollbars);

      /**
       * element : showsLocation of type {http://www.w3.org/2001/XMLSchema}boolean
       * java type: java.lang.Boolean
       */

      public java.lang.Boolean getShowsLocation();

      public void setShowsLocation(java.lang.Boolean showsLocation);

      /**
       * element : showsStatus of type {http://www.w3.org/2001/XMLSchema}boolean
       * java type: java.lang.Boolean
       */

      public java.lang.Boolean getShowsStatus();

      public void setShowsStatus(java.lang.Boolean showsStatus);

      /**
       * element : toolbar of type {http://www.w3.org/2001/XMLSchema}boolean
       * java type: java.lang.Boolean
       */

      public java.lang.Boolean getToolbar();

      public void setToolbar(java.lang.Boolean toolbar);

      /**
       * element : url of type {http://www.w3.org/2001/XMLSchema}string
       * java type: java.lang.String
       */

      public java.lang.String getUrl();

      public void setUrl(java.lang.String url);

      /**
       * element : width of type {http://www.w3.org/2001/XMLSchema}int
       * java type: java.lang.Integer
       */

      public java.lang.Integer getWidth();

      public void setWidth(java.lang.Integer width);

      /**
       * element : windowPosition of type {urn:partner.soap.sforce.com}WebLinkPosition
       * java type: com.sforce.soap.partner.WebLinkPosition
       */

      public com.sforce.soap.partner.WebLinkPosition getWindowPosition();

      public void setWindowPosition(com.sforce.soap.partner.WebLinkPosition windowPosition);


}
