package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IDescribeSoqlListViews_element  {

      /**
       * element : request of type {urn:partner.soap.sforce.com}DescribeSoqlListViewsRequest
       * java type: com.sforce.soap.partner.DescribeSoqlListViewsRequest
       */

      public com.sforce.soap.partner.IDescribeSoqlListViewsRequest getRequest();

      public void setRequest(com.sforce.soap.partner.IDescribeSoqlListViewsRequest request);


}
