package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IDescribeFlexiPages_element  {

      /**
       * element : flexiPages of type {http://www.w3.org/2001/XMLSchema}string
       * java type: java.lang.String[]
       */

      public java.lang.String[] getFlexiPages();

      public void setFlexiPages(java.lang.String[] flexiPages);


}
