package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IDescribeKnowledgeSettingsResponse_element  {

      /**
       * element : result of type {urn:partner.soap.sforce.com}KnowledgeSettings
       * java type: com.sforce.soap.partner.KnowledgeSettings
       */

      public com.sforce.soap.partner.IKnowledgeSettings getResult();

      public void setResult(com.sforce.soap.partner.IKnowledgeSettings result);


}
