package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IDescribeSObjectListViews_element  {

      /**
       * element : sObjectType of type {http://www.w3.org/2001/XMLSchema}string
       * java type: java.lang.String
       */

      public java.lang.String getSObjectType();

      public void setSObjectType(java.lang.String sObjectType);

      /**
       * element : recentsOnly of type {http://www.w3.org/2001/XMLSchema}boolean
       * java type: boolean
       */

      public boolean getRecentsOnly();

      public boolean isRecentsOnly();

      public void setRecentsOnly(boolean recentsOnly);

      /**
       * element : isSoqlCompatible of type {urn:partner.soap.sforce.com}listViewIsSoqlCompatible
       * java type: com.sforce.soap.partner.ListViewIsSoqlCompatible
       */

      public com.sforce.soap.partner.ListViewIsSoqlCompatible getIsSoqlCompatible();

      public void setIsSoqlCompatible(com.sforce.soap.partner.ListViewIsSoqlCompatible isSoqlCompatible);

      /**
       * element : limit of type {http://www.w3.org/2001/XMLSchema}int
       * java type: int
       */

      public int getLimit();

      public void setLimit(int limit);

      /**
       * element : offset of type {http://www.w3.org/2001/XMLSchema}int
       * java type: int
       */

      public int getOffset();

      public void setOffset(int offset);


}
