package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IDescribeApprovalLayout  {

      /**
       * element : id of type {urn:partner.soap.sforce.com}ID
       * java type: java.lang.String
       */

      public java.lang.String getId();

      public void setId(java.lang.String id);

      /**
       * element : label of type {http://www.w3.org/2001/XMLSchema}string
       * java type: java.lang.String
       */

      public java.lang.String getLabel();

      public void setLabel(java.lang.String label);

      /**
       * element : layoutItems of type {urn:partner.soap.sforce.com}DescribeLayoutItem
       * java type: com.sforce.soap.partner.DescribeLayoutItem[]
       */

      public com.sforce.soap.partner.IDescribeLayoutItem[] getLayoutItems();

      public void setLayoutItems(com.sforce.soap.partner.IDescribeLayoutItem[] layoutItems);

      /**
       * element : name of type {http://www.w3.org/2001/XMLSchema}string
       * java type: java.lang.String
       */

      public java.lang.String getName();

      public void setName(java.lang.String name);


}
