package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IDescribeQuickActionListResult  {

      /**
       * element : quickActionListItems of type {urn:partner.soap.sforce.com}DescribeQuickActionListItemResult
       * java type: com.sforce.soap.partner.DescribeQuickActionListItemResult[]
       */

      public com.sforce.soap.partner.IDescribeQuickActionListItemResult[] getQuickActionListItems();

      public void setQuickActionListItems(com.sforce.soap.partner.IDescribeQuickActionListItemResult[] quickActionListItems);


}
