package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IDescribeApprovalLayoutResponse_element  {

      /**
       * element : result of type {urn:partner.soap.sforce.com}DescribeApprovalLayoutResult
       * java type: com.sforce.soap.partner.DescribeApprovalLayoutResult
       */

      public com.sforce.soap.partner.IDescribeApprovalLayoutResult getResult();

      public void setResult(com.sforce.soap.partner.IDescribeApprovalLayoutResult result);


}
