package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IDescribeLayoutResponse_element  {

      /**
       * element : result of type {urn:partner.soap.sforce.com}DescribeLayoutResult
       * java type: com.sforce.soap.partner.DescribeLayoutResult
       */

      public com.sforce.soap.partner.IDescribeLayoutResult getResult();

      public void setResult(com.sforce.soap.partner.IDescribeLayoutResult result);


}
