package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IDescribeQuickActions_element  {

      /**
       * element : quickActions of type {http://www.w3.org/2001/XMLSchema}string
       * java type: java.lang.String[]
       */

      public java.lang.String[] getQuickActions();

      public void setQuickActions(java.lang.String[] quickActions);


}
