package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IDescribeQuickActionDefaultValue  {

      /**
       * element : defaultValue of type {http://www.w3.org/2001/XMLSchema}string
       * java type: java.lang.String
       */

      public java.lang.String getDefaultValue();

      public void setDefaultValue(java.lang.String defaultValue);

      /**
       * element : field of type {http://www.w3.org/2001/XMLSchema}string
       * java type: java.lang.String
       */

      public java.lang.String getField();

      public void setField(java.lang.String field);


}
