package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IDescribeAllTabsResponse_element  {

      /**
       * element : result of type {urn:partner.soap.sforce.com}DescribeTab
       * java type: com.sforce.soap.partner.DescribeTab[]
       */

      public com.sforce.soap.partner.IDescribeTab[] getResult();

      public void setResult(com.sforce.soap.partner.IDescribeTab[] result);


}
