package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IDescribeSObjectResult  {

      /**
       * element : actionOverrides of type {urn:partner.soap.sforce.com}ActionOverride
       * java type: com.sforce.soap.partner.ActionOverride[]
       */

      public com.sforce.soap.partner.IActionOverride[] getActionOverrides();

      public void setActionOverrides(com.sforce.soap.partner.IActionOverride[] actionOverrides);

      /**
       * element : activateable of type {http://www.w3.org/2001/XMLSchema}boolean
       * java type: boolean
       */

      public boolean getActivateable();

      public boolean isActivateable();

      public void setActivateable(boolean activateable);

      /**
       * element : childRelationships of type {urn:partner.soap.sforce.com}ChildRelationship
       * java type: com.sforce.soap.partner.ChildRelationship[]
       */

      public com.sforce.soap.partner.IChildRelationship[] getChildRelationships();

      public void setChildRelationships(com.sforce.soap.partner.IChildRelationship[] childRelationships);

      /**
       * element : compactLayoutable of type {http://www.w3.org/2001/XMLSchema}boolean
       * java type: boolean
       */

      public boolean getCompactLayoutable();

      public boolean isCompactLayoutable();

      public void setCompactLayoutable(boolean compactLayoutable);

      /**
       * element : createable of type {http://www.w3.org/2001/XMLSchema}boolean
       * java type: boolean
       */

      public boolean getCreateable();

      public boolean isCreateable();

      public void setCreateable(boolean createable);

      /**
       * element : custom of type {http://www.w3.org/2001/XMLSchema}boolean
       * java type: boolean
       */

      public boolean getCustom();

      public boolean isCustom();

      public void setCustom(boolean custom);

      /**
       * element : customSetting of type {http://www.w3.org/2001/XMLSchema}boolean
       * java type: boolean
       */

      public boolean getCustomSetting();

      public boolean isCustomSetting();

      public void setCustomSetting(boolean customSetting);

      /**
       * element : deletable of type {http://www.w3.org/2001/XMLSchema}boolean
       * java type: boolean
       */

      public boolean getDeletable();

      public boolean isDeletable();

      public void setDeletable(boolean deletable);

      /**
       * element : deprecatedAndHidden of type {http://www.w3.org/2001/XMLSchema}boolean
       * java type: boolean
       */

      public boolean getDeprecatedAndHidden();

      public boolean isDeprecatedAndHidden();

      public void setDeprecatedAndHidden(boolean deprecatedAndHidden);

      /**
       * element : feedEnabled of type {http://www.w3.org/2001/XMLSchema}boolean
       * java type: boolean
       */

      public boolean getFeedEnabled();

      public boolean isFeedEnabled();

      public void setFeedEnabled(boolean feedEnabled);

      /**
       * element : fields of type {urn:partner.soap.sforce.com}Field
       * java type: com.sforce.soap.partner.Field[]
       */

      public com.sforce.soap.partner.IField[] getFields();

      public void setFields(com.sforce.soap.partner.IField[] fields);

      /**
       * element : keyPrefix of type {http://www.w3.org/2001/XMLSchema}string
       * java type: java.lang.String
       */

      public java.lang.String getKeyPrefix();

      public void setKeyPrefix(java.lang.String keyPrefix);

      /**
       * element : label of type {http://www.w3.org/2001/XMLSchema}string
       * java type: java.lang.String
       */

      public java.lang.String getLabel();

      public void setLabel(java.lang.String label);

      /**
       * element : labelPlural of type {http://www.w3.org/2001/XMLSchema}string
       * java type: java.lang.String
       */

      public java.lang.String getLabelPlural();

      public void setLabelPlural(java.lang.String labelPlural);

      /**
       * element : layoutable of type {http://www.w3.org/2001/XMLSchema}boolean
       * java type: boolean
       */

      public boolean getLayoutable();

      public boolean isLayoutable();

      public void setLayoutable(boolean layoutable);

      /**
       * element : mergeable of type {http://www.w3.org/2001/XMLSchema}boolean
       * java type: boolean
       */

      public boolean getMergeable();

      public boolean isMergeable();

      public void setMergeable(boolean mergeable);

      /**
       * element : name of type {http://www.w3.org/2001/XMLSchema}string
       * java type: java.lang.String
       */

      public java.lang.String getName();

      public void setName(java.lang.String name);

      /**
       * element : namedLayoutInfos of type {urn:partner.soap.sforce.com}NamedLayoutInfo
       * java type: com.sforce.soap.partner.NamedLayoutInfo[]
       */

      public com.sforce.soap.partner.INamedLayoutInfo[] getNamedLayoutInfos();

      public void setNamedLayoutInfos(com.sforce.soap.partner.INamedLayoutInfo[] namedLayoutInfos);

      /**
       * element : queryable of type {http://www.w3.org/2001/XMLSchema}boolean
       * java type: boolean
       */

      public boolean getQueryable();

      public boolean isQueryable();

      public void setQueryable(boolean queryable);

      /**
       * element : recordTypeInfos of type {urn:partner.soap.sforce.com}RecordTypeInfo
       * java type: com.sforce.soap.partner.RecordTypeInfo[]
       */

      public com.sforce.soap.partner.IRecordTypeInfo[] getRecordTypeInfos();

      public void setRecordTypeInfos(com.sforce.soap.partner.IRecordTypeInfo[] recordTypeInfos);

      /**
       * element : replicateable of type {http://www.w3.org/2001/XMLSchema}boolean
       * java type: boolean
       */

      public boolean getReplicateable();

      public boolean isReplicateable();

      public void setReplicateable(boolean replicateable);

      /**
       * element : retrieveable of type {http://www.w3.org/2001/XMLSchema}boolean
       * java type: boolean
       */

      public boolean getRetrieveable();

      public boolean isRetrieveable();

      public void setRetrieveable(boolean retrieveable);

      /**
       * element : searchLayoutable of type {http://www.w3.org/2001/XMLSchema}boolean
       * java type: boolean
       */

      public boolean getSearchLayoutable();

      public boolean isSearchLayoutable();

      public void setSearchLayoutable(boolean searchLayoutable);

      /**
       * element : searchable of type {http://www.w3.org/2001/XMLSchema}boolean
       * java type: boolean
       */

      public boolean getSearchable();

      public boolean isSearchable();

      public void setSearchable(boolean searchable);

      /**
       * element : triggerable of type {http://www.w3.org/2001/XMLSchema}boolean
       * java type: boolean
       */

      public boolean getTriggerable();

      public boolean isTriggerable();

      public void setTriggerable(boolean triggerable);

      /**
       * element : undeletable of type {http://www.w3.org/2001/XMLSchema}boolean
       * java type: boolean
       */

      public boolean getUndeletable();

      public boolean isUndeletable();

      public void setUndeletable(boolean undeletable);

      /**
       * element : updateable of type {http://www.w3.org/2001/XMLSchema}boolean
       * java type: boolean
       */

      public boolean getUpdateable();

      public boolean isUpdateable();

      public void setUpdateable(boolean updateable);

      /**
       * element : urlDetail of type {http://www.w3.org/2001/XMLSchema}string
       * java type: java.lang.String
       */

      public java.lang.String getUrlDetail();

      public void setUrlDetail(java.lang.String urlDetail);

      /**
       * element : urlEdit of type {http://www.w3.org/2001/XMLSchema}string
       * java type: java.lang.String
       */

      public java.lang.String getUrlEdit();

      public void setUrlEdit(java.lang.String urlEdit);

      /**
       * element : urlNew of type {http://www.w3.org/2001/XMLSchema}string
       * java type: java.lang.String
       */

      public java.lang.String getUrlNew();

      public void setUrlNew(java.lang.String urlNew);


}
