package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IDescribeSoftphoneLayoutItem  {

      /**
       * element : itemApiName of type {http://www.w3.org/2001/XMLSchema}string
       * java type: java.lang.String
       */

      public java.lang.String getItemApiName();

      public void setItemApiName(java.lang.String itemApiName);


}
