package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IDescribeAppMenuResult  {

      /**
       * element : appMenuItems of type {urn:partner.soap.sforce.com}DescribeAppMenuItem
       * java type: com.sforce.soap.partner.DescribeAppMenuItem[]
       */

      public com.sforce.soap.partner.IDescribeAppMenuItem[] getAppMenuItems();

      public void setAppMenuItems(com.sforce.soap.partner.IDescribeAppMenuItem[] appMenuItems);


}
