package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IDescribeSearchLayoutsResponse_element  {

      /**
       * element : result of type {urn:partner.soap.sforce.com}DescribeSearchLayoutResult
       * java type: com.sforce.soap.partner.DescribeSearchLayoutResult[]
       */

      public com.sforce.soap.partner.IDescribeSearchLayoutResult[] getResult();

      public void setResult(com.sforce.soap.partner.IDescribeSearchLayoutResult[] result);


}
