package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IDescribePrimaryCompactLayoutsResponse_element  {

      /**
       * element : result of type {urn:partner.soap.sforce.com}DescribeCompactLayout
       * java type: com.sforce.soap.partner.DescribeCompactLayout[]
       */

      public com.sforce.soap.partner.IDescribeCompactLayout[] getResult();

      public void setResult(com.sforce.soap.partner.IDescribeCompactLayout[] result);


}
