package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IDescribeColor  {

      /**
       * element : color of type {http://www.w3.org/2001/XMLSchema}string
       * java type: java.lang.String
       */

      public java.lang.String getColor();

      public void setColor(java.lang.String color);

      /**
       * element : context of type {http://www.w3.org/2001/XMLSchema}string
       * java type: java.lang.String
       */

      public java.lang.String getContext();

      public void setContext(java.lang.String context);

      /**
       * element : theme of type {http://www.w3.org/2001/XMLSchema}string
       * java type: java.lang.String
       */

      public java.lang.String getTheme();

      public void setTheme(java.lang.String theme);


}
