package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IEmailHeader_element  {

      /**
       * element : triggerAutoResponseEmail of type {http://www.w3.org/2001/XMLSchema}boolean
       * java type: boolean
       */

      public boolean getTriggerAutoResponseEmail();

      public boolean isTriggerAutoResponseEmail();

      public void setTriggerAutoResponseEmail(boolean triggerAutoResponseEmail);

      /**
       * element : triggerOtherEmail of type {http://www.w3.org/2001/XMLSchema}boolean
       * java type: boolean
       */

      public boolean getTriggerOtherEmail();

      public boolean isTriggerOtherEmail();

      public void setTriggerOtherEmail(boolean triggerOtherEmail);

      /**
       * element : triggerUserEmail of type {http://www.w3.org/2001/XMLSchema}boolean
       * java type: boolean
       */

      public boolean getTriggerUserEmail();

      public boolean isTriggerUserEmail();

      public void setTriggerUserEmail(boolean triggerUserEmail);


}
