package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IFieldComponent extends com.sforce.soap.partner.IDescribeLayoutComponent {

      /**
       * element : field of type {urn:partner.soap.sforce.com}Field
       * java type: com.sforce.soap.partner.Field
       */

      public com.sforce.soap.partner.IField getField();

      public void setField(com.sforce.soap.partner.IField field);


}
