package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IFieldLayoutComponent extends com.sforce.soap.partner.IDescribeLayoutComponent {

      /**
       * element : components of type {urn:partner.soap.sforce.com}DescribeLayoutComponent
       * java type: com.sforce.soap.partner.DescribeLayoutComponent[]
       */

      public com.sforce.soap.partner.IDescribeLayoutComponent[] getComponents();

      public void setComponents(com.sforce.soap.partner.IDescribeLayoutComponent[] components);

      /**
       * element : fieldType of type {urn:partner.soap.sforce.com}fieldType
       * java type: com.sforce.soap.partner.FieldType
       */

      public com.sforce.soap.partner.FieldType getFieldType();

      public void setFieldType(com.sforce.soap.partner.FieldType fieldType);


}
