package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IGetServerTimestampResult  {

      /**
       * element : timestamp of type {http://www.w3.org/2001/XMLSchema}dateTime
       * java type: java.util.Calendar
       */

      public java.util.Calendar getTimestamp();

      public void setTimestamp(java.util.Calendar timestamp);


}
