package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IGetServerTimestampResponse_element  {

      /**
       * element : result of type {urn:partner.soap.sforce.com}GetServerTimestampResult
       * java type: com.sforce.soap.partner.GetServerTimestampResult
       */

      public com.sforce.soap.partner.IGetServerTimestampResult getResult();

      public void setResult(com.sforce.soap.partner.IGetServerTimestampResult result);


}
