package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface ILeadConvertResult  {

      /**
       * element : accountId of type {urn:partner.soap.sforce.com}ID
       * java type: java.lang.String
       */

      public java.lang.String getAccountId();

      public void setAccountId(java.lang.String accountId);

      /**
       * element : contactId of type {urn:partner.soap.sforce.com}ID
       * java type: java.lang.String
       */

      public java.lang.String getContactId();

      public void setContactId(java.lang.String contactId);

      /**
       * element : errors of type {urn:partner.soap.sforce.com}Error
       * java type: com.sforce.soap.partner.Error[]
       */

      public com.sforce.soap.partner.IError[] getErrors();

      public void setErrors(com.sforce.soap.partner.IError[] errors);

      /**
       * element : leadId of type {urn:partner.soap.sforce.com}ID
       * java type: java.lang.String
       */

      public java.lang.String getLeadId();

      public void setLeadId(java.lang.String leadId);

      /**
       * element : opportunityId of type {urn:partner.soap.sforce.com}ID
       * java type: java.lang.String
       */

      public java.lang.String getOpportunityId();

      public void setOpportunityId(java.lang.String opportunityId);

      /**
       * element : success of type {http://www.w3.org/2001/XMLSchema}boolean
       * java type: boolean
       */

      public boolean getSuccess();

      public boolean isSuccess();

      public void setSuccess(boolean success);


}
