package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface ILimitInfoHeader_element  {

      /**
       * element : limitInfo of type {urn:partner.soap.sforce.com}LimitInfo
       * java type: com.sforce.soap.partner.LimitInfo[]
       */

      public com.sforce.soap.partner.ILimitInfo[] getLimitInfo();

      public void setLimitInfo(com.sforce.soap.partner.ILimitInfo[] limitInfo);


}
