package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IListViewColumn  {

      /**
       * element : ascendingLabel of type {http://www.w3.org/2001/XMLSchema}string
       * java type: java.lang.String
       */

      public java.lang.String getAscendingLabel();

      public void setAscendingLabel(java.lang.String ascendingLabel);

      /**
       * element : descendingLabel of type {http://www.w3.org/2001/XMLSchema}string
       * java type: java.lang.String
       */

      public java.lang.String getDescendingLabel();

      public void setDescendingLabel(java.lang.String descendingLabel);

      /**
       * element : fieldNameOrPath of type {http://www.w3.org/2001/XMLSchema}string
       * java type: java.lang.String
       */

      public java.lang.String getFieldNameOrPath();

      public void setFieldNameOrPath(java.lang.String fieldNameOrPath);

      /**
       * element : hidden of type {http://www.w3.org/2001/XMLSchema}boolean
       * java type: boolean
       */

      public boolean getHidden();

      public boolean isHidden();

      public void setHidden(boolean hidden);

      /**
       * element : label of type {http://www.w3.org/2001/XMLSchema}string
       * java type: java.lang.String
       */

      public java.lang.String getLabel();

      public void setLabel(java.lang.String label);

      /**
       * element : selectListItem of type {http://www.w3.org/2001/XMLSchema}string
       * java type: java.lang.String
       */

      public java.lang.String getSelectListItem();

      public void setSelectListItem(java.lang.String selectListItem);

      /**
       * element : sortDirection of type {urn:partner.soap.sforce.com}orderByDirection
       * java type: com.sforce.soap.partner.OrderByDirection
       */

      public com.sforce.soap.partner.OrderByDirection getSortDirection();

      public void setSortDirection(com.sforce.soap.partner.OrderByDirection sortDirection);

      /**
       * element : sortIndex of type {http://www.w3.org/2001/XMLSchema}int
       * java type: java.lang.Integer
       */

      public java.lang.Integer getSortIndex();

      public void setSortIndex(java.lang.Integer sortIndex);

      /**
       * element : sortable of type {http://www.w3.org/2001/XMLSchema}boolean
       * java type: boolean
       */

      public boolean getSortable();

      public boolean isSortable();

      public void setSortable(boolean sortable);

      /**
       * element : type of type {urn:partner.soap.sforce.com}fieldType
       * java type: com.sforce.soap.partner.FieldType
       */

      public com.sforce.soap.partner.FieldType getType();

      public void setType(com.sforce.soap.partner.FieldType type);


}
