package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IListViewRecord  {

      /**
       * element : columns of type {urn:partner.soap.sforce.com}ListViewRecordColumn
       * java type: com.sforce.soap.partner.ListViewRecordColumn[]
       */

      public com.sforce.soap.partner.IListViewRecordColumn[] getColumns();

      public void setColumns(com.sforce.soap.partner.IListViewRecordColumn[] columns);


}
