package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface ILocaleOptions_element  {

      /**
       * element : language of type {http://www.w3.org/2001/XMLSchema}string
       * java type: java.lang.String
       */

      public java.lang.String getLanguage();

      public void setLanguage(java.lang.String language);

      /**
       * element : localizeErrors of type {http://www.w3.org/2001/XMLSchema}boolean
       * java type: boolean
       */

      public boolean getLocalizeErrors();

      public boolean isLocalizeErrors();

      public void setLocalizeErrors(boolean localizeErrors);


}
