package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface ILoginScopeHeader_element  {

      /**
       * element : organizationId of type {urn:partner.soap.sforce.com}ID
       * java type: java.lang.String
       */

      public java.lang.String getOrganizationId();

      public void setOrganizationId(java.lang.String organizationId);

      /**
       * element : portalId of type {urn:partner.soap.sforce.com}ID
       * java type: java.lang.String
       */

      public java.lang.String getPortalId();

      public void setPortalId(java.lang.String portalId);


}
