package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IMatchRecord  {

      /**
       * element : additionalInformation of type {urn:partner.soap.sforce.com}AdditionalInformationMap
       * java type: com.sforce.soap.partner.AdditionalInformationMap[]
       */

      public com.sforce.soap.partner.IAdditionalInformationMap[] getAdditionalInformation();

      public void setAdditionalInformation(com.sforce.soap.partner.IAdditionalInformationMap[] additionalInformation);

      /**
       * element : fieldDiffs of type {urn:partner.soap.sforce.com}FieldDiff
       * java type: com.sforce.soap.partner.FieldDiff[]
       */

      public com.sforce.soap.partner.IFieldDiff[] getFieldDiffs();

      public void setFieldDiffs(com.sforce.soap.partner.IFieldDiff[] fieldDiffs);

      /**
       * element : matchConfidence of type {http://www.w3.org/2001/XMLSchema}double
       * java type: double
       */

      public double getMatchConfidence();

      public void setMatchConfidence(double matchConfidence);

      /**
       * element : record of type {urn:sobject.partner.soap.sforce.com}sObject
       * java type: com.sforce.soap.partner.sobject.SObject
       */

      public com.sforce.soap.partner.sobject.ISObject getRecord();

      public void setRecord(com.sforce.soap.partner.sobject.ISObject record);


}
