package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IPackageVersionHeader_element  {

      /**
       * element : packageVersions of type {urn:partner.soap.sforce.com}PackageVersion
       * java type: com.sforce.soap.partner.PackageVersion[]
       */

      public com.sforce.soap.partner.IPackageVersion[] getPackageVersions();

      public void setPackageVersions(com.sforce.soap.partner.IPackageVersion[] packageVersions);


}
