package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IProcessSubmitRequest extends com.sforce.soap.partner.IProcessRequest {

      /**
       * element : objectId of type {urn:partner.soap.sforce.com}ID
       * java type: java.lang.String
       */

      public java.lang.String getObjectId();

      public void setObjectId(java.lang.String objectId);

      /**
       * element : submitterId of type {urn:partner.soap.sforce.com}ID
       * java type: java.lang.String
       */

      public java.lang.String getSubmitterId();

      public void setSubmitterId(java.lang.String submitterId);

      /**
       * element : processDefinitionNameOrId of type {http://www.w3.org/2001/XMLSchema}string
       * java type: java.lang.String
       */

      public java.lang.String getProcessDefinitionNameOrId();

      public void setProcessDefinitionNameOrId(java.lang.String processDefinitionNameOrId);

      /**
       * element : skipEntryCriteria of type {http://www.w3.org/2001/XMLSchema}boolean
       * java type: java.lang.Boolean
       */

      public java.lang.Boolean getSkipEntryCriteria();

      public void setSkipEntryCriteria(java.lang.Boolean skipEntryCriteria);


}
