package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IQueryOptions_element  {

      /**
       * element : batchSize of type {http://www.w3.org/2001/XMLSchema}int
       * java type: int
       */

      public int getBatchSize();

      public void setBatchSize(int batchSize);


}
