package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IRelatedList  {

      /**
       * element : accessLevelRequiredForCreate of type {urn:partner.soap.sforce.com}ShareAccessLevel
       * java type: com.sforce.soap.partner.ShareAccessLevel
       */

      public com.sforce.soap.partner.ShareAccessLevel getAccessLevelRequiredForCreate();

      public void setAccessLevelRequiredForCreate(com.sforce.soap.partner.ShareAccessLevel accessLevelRequiredForCreate);

      /**
       * element : buttons of type {urn:partner.soap.sforce.com}DescribeLayoutButton
       * java type: com.sforce.soap.partner.DescribeLayoutButton[]
       */

      public com.sforce.soap.partner.IDescribeLayoutButton[] getButtons();

      public void setButtons(com.sforce.soap.partner.IDescribeLayoutButton[] buttons);

      /**
       * element : columns of type {urn:partner.soap.sforce.com}RelatedListColumn
       * java type: com.sforce.soap.partner.RelatedListColumn[]
       */

      public com.sforce.soap.partner.IRelatedListColumn[] getColumns();

      public void setColumns(com.sforce.soap.partner.IRelatedListColumn[] columns);

      /**
       * element : custom of type {http://www.w3.org/2001/XMLSchema}boolean
       * java type: boolean
       */

      public boolean getCustom();

      public boolean isCustom();

      public void setCustom(boolean custom);

      /**
       * element : field of type {http://www.w3.org/2001/XMLSchema}string
       * java type: java.lang.String
       */

      public java.lang.String getField();

      public void setField(java.lang.String field);

      /**
       * element : label of type {http://www.w3.org/2001/XMLSchema}string
       * java type: java.lang.String
       */

      public java.lang.String getLabel();

      public void setLabel(java.lang.String label);

      /**
       * element : limitRows of type {http://www.w3.org/2001/XMLSchema}int
       * java type: int
       */

      public int getLimitRows();

      public void setLimitRows(int limitRows);

      /**
       * element : name of type {http://www.w3.org/2001/XMLSchema}string
       * java type: java.lang.String
       */

      public java.lang.String getName();

      public void setName(java.lang.String name);

      /**
       * element : sobject of type {http://www.w3.org/2001/XMLSchema}string
       * java type: java.lang.String
       */

      public java.lang.String getSobject();

      public void setSobject(java.lang.String sobject);

      /**
       * element : sort of type {urn:partner.soap.sforce.com}RelatedListSort
       * java type: com.sforce.soap.partner.RelatedListSort[]
       */

      public com.sforce.soap.partner.IRelatedListSort[] getSort();

      public void setSort(com.sforce.soap.partner.IRelatedListSort[] sort);


}
