package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IRelatedListSort  {

      /**
       * element : ascending of type {http://www.w3.org/2001/XMLSchema}boolean
       * java type: boolean
       */

      public boolean getAscending();

      public boolean isAscending();

      public void setAscending(boolean ascending);

      /**
       * element : column of type {http://www.w3.org/2001/XMLSchema}string
       * java type: java.lang.String
       */

      public java.lang.String getColumn();

      public void setColumn(java.lang.String column);


}
