package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IResetPasswordResponse_element  {

      /**
       * element : result of type {urn:partner.soap.sforce.com}ResetPasswordResult
       * java type: com.sforce.soap.partner.ResetPasswordResult
       */

      public com.sforce.soap.partner.IResetPasswordResult getResult();

      public void setResult(com.sforce.soap.partner.IResetPasswordResult result);


}
