package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface ISearchRecord  {

      /**
       * element : record of type {urn:sobject.partner.soap.sforce.com}sObject
       * java type: com.sforce.soap.partner.sobject.SObject
       */

      public com.sforce.soap.partner.sobject.ISObject getRecord();

      public void setRecord(com.sforce.soap.partner.sobject.ISObject record);

      /**
       * element : snippet of type {urn:partner.soap.sforce.com}SearchSnippet
       * java type: com.sforce.soap.partner.SearchSnippet
       */

      public com.sforce.soap.partner.ISearchSnippet getSnippet();

      public void setSnippet(com.sforce.soap.partner.ISearchSnippet snippet);


}
