package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface ISetPasswordResponse_element  {

      /**
       * element : result of type {urn:partner.soap.sforce.com}SetPasswordResult
       * java type: com.sforce.soap.partner.SetPasswordResult
       */

      public com.sforce.soap.partner.ISetPasswordResult getResult();

      public void setResult(com.sforce.soap.partner.ISetPasswordResult result);


}
