package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IUpdate_element  {

      /**
       * element : sObjects of type {urn:sobject.partner.soap.sforce.com}sObject
       * java type: com.sforce.soap.partner.sobject.SObject[]
       */

      public com.sforce.soap.partner.sobject.ISObject[] getSObjects();

      public void setSObjects(com.sforce.soap.partner.sobject.ISObject[] sObjects);


}
