package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IUpsertResponse_element  {

      /**
       * element : result of type {urn:partner.soap.sforce.com}UpsertResult
       * java type: com.sforce.soap.partner.UpsertResult[]
       */

      public com.sforce.soap.partner.IUpsertResult[] getResult();

      public void setResult(com.sforce.soap.partner.IUpsertResult[] result);


}
