package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IUserTerritoryDeleteHeader_element  {

      /**
       * element : transferToUserId of type {urn:partner.soap.sforce.com}ID
       * java type: java.lang.String
       */

      public java.lang.String getTransferToUserId();

      public void setTransferToUserId(java.lang.String transferToUserId);


}
