package com.sforce.soap.partner;

import java.util.EnumSet;
import java.util.HashMap;
import java.util.Map;

/**
 * Generated by SimpleTypeCodeGenerator.java. Please do not edit.
 */
public enum ListViewIsSoqlCompatible {


  
	/**
	 * Enumeration  : TRUE
	 */
	TRUE("TRUE"),

  
	/**
	 * Enumeration  : FALSE
	 */
	FALSE("FALSE"),

  
	/**
	 * Enumeration  : ALL
	 */
	ALL("ALL"),

;

	public static Map<String, String> valuesToEnums;

	static {
   		valuesToEnums = new HashMap<String, String>();
   		for (ListViewIsSoqlCompatible e : EnumSet.allOf(ListViewIsSoqlCompatible.class)) {
   			valuesToEnums.put(e.toString(), e.name());
   		}
   	}

   	private String value;

   	private ListViewIsSoqlCompatible(String value) {
   		this.value = value;
   	}

   	@Override
   	public String toString() {
   		return value;
   	}
}
