package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public class MatchResult implements com.sforce.ws.bind.XMLizable , IMatchResult{

    /**
     * Constructor
     */
    public MatchResult() {}

    /**
     * element : errors of type {urn:partner.soap.sforce.com}Error
     * java type: com.sforce.soap.partner.Error[]
     */
    private static final com.sforce.ws.bind.TypeInfo errors__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","errors","urn:partner.soap.sforce.com","Error",0,-1,true);

    private boolean errors__is_set = false;

    private com.sforce.soap.partner.Error[] errors = new com.sforce.soap.partner.Error[0];

    @Override
    public com.sforce.soap.partner.Error[] getErrors() {
      return errors;
    }

    @Override
    public void setErrors(com.sforce.soap.partner.IError[] errors) {
      this.errors = castArray(com.sforce.soap.partner.Error.class, errors);
      errors__is_set = true;
    }

    protected void setErrors(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, errors__typeInfo)) {
        setErrors((com.sforce.soap.partner.Error[])__typeMapper.readObject(__in, errors__typeInfo, com.sforce.soap.partner.Error[].class));
      }
    }

    /**
     * element : entityType of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo entityType__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","entityType","http://www.w3.org/2001/XMLSchema","string",1,1,true);

    private boolean entityType__is_set = false;

    private java.lang.String entityType;

    @Override
    public java.lang.String getEntityType() {
      return entityType;
    }

    @Override
    public void setEntityType(java.lang.String entityType) {
      this.entityType = entityType;
      entityType__is_set = true;
    }

    protected void setEntityType(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, entityType__typeInfo)) {
        setEntityType(__typeMapper.readString(__in, entityType__typeInfo, java.lang.String.class));
      }
    }

    /**
     * element : matchEngine of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo matchEngine__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","matchEngine","http://www.w3.org/2001/XMLSchema","string",1,1,true);

    private boolean matchEngine__is_set = false;

    private java.lang.String matchEngine;

    @Override
    public java.lang.String getMatchEngine() {
      return matchEngine;
    }

    @Override
    public void setMatchEngine(java.lang.String matchEngine) {
      this.matchEngine = matchEngine;
      matchEngine__is_set = true;
    }

    protected void setMatchEngine(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, matchEngine__typeInfo)) {
        setMatchEngine(__typeMapper.readString(__in, matchEngine__typeInfo, java.lang.String.class));
      }
    }

    /**
     * element : matchRecords of type {urn:partner.soap.sforce.com}MatchRecord
     * java type: com.sforce.soap.partner.MatchRecord[]
     */
    private static final com.sforce.ws.bind.TypeInfo matchRecords__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","matchRecords","urn:partner.soap.sforce.com","MatchRecord",0,-1,true);

    private boolean matchRecords__is_set = false;

    private com.sforce.soap.partner.MatchRecord[] matchRecords = new com.sforce.soap.partner.MatchRecord[0];

    @Override
    public com.sforce.soap.partner.MatchRecord[] getMatchRecords() {
      return matchRecords;
    }

    @Override
    public void setMatchRecords(com.sforce.soap.partner.IMatchRecord[] matchRecords) {
      this.matchRecords = castArray(com.sforce.soap.partner.MatchRecord.class, matchRecords);
      matchRecords__is_set = true;
    }

    protected void setMatchRecords(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, matchRecords__typeInfo)) {
        setMatchRecords((com.sforce.soap.partner.MatchRecord[])__typeMapper.readObject(__in, matchRecords__typeInfo, com.sforce.soap.partner.MatchRecord[].class));
      }
    }

    /**
     * element : rule of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo rule__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","rule","http://www.w3.org/2001/XMLSchema","string",1,1,true);

    private boolean rule__is_set = false;

    private java.lang.String rule;

    @Override
    public java.lang.String getRule() {
      return rule;
    }

    @Override
    public void setRule(java.lang.String rule) {
      this.rule = rule;
      rule__is_set = true;
    }

    protected void setRule(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, rule__typeInfo)) {
        setRule(__typeMapper.readString(__in, rule__typeInfo, java.lang.String.class));
      }
    }

    /**
     * element : size of type {http://www.w3.org/2001/XMLSchema}int
     * java type: int
     */
    private static final com.sforce.ws.bind.TypeInfo size__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","size","http://www.w3.org/2001/XMLSchema","int",1,1,true);

    private boolean size__is_set = false;

    private int size;

    @Override
    public int getSize() {
      return size;
    }

    @Override
    public void setSize(int size) {
      this.size = size;
      size__is_set = true;
    }

    protected void setSize(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, size__typeInfo)) {
        setSize((int)__typeMapper.readInt(__in, size__typeInfo, int.class));
      }
    }

    /**
     * element : success of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private static final com.sforce.ws.bind.TypeInfo success__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","success","http://www.w3.org/2001/XMLSchema","boolean",1,1,true);

    private boolean success__is_set = false;

    private boolean success;

    @Override
    public boolean getSuccess() {
      return success;
    }

    @Override
    public boolean isSuccess() {
      return success;
    }

    @Override
    public void setSuccess(boolean success) {
      this.success = success;
      success__is_set = true;
    }

    protected void setSuccess(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, success__typeInfo)) {
        setSuccess(__typeMapper.readBoolean(__in, success__typeInfo, boolean.class));
      }
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       __typeMapper.writeObject(__out, errors__typeInfo, errors, errors__is_set);
       __typeMapper.writeString(__out, entityType__typeInfo, entityType, entityType__is_set);
       __typeMapper.writeString(__out, matchEngine__typeInfo, matchEngine, matchEngine__is_set);
       __typeMapper.writeObject(__out, matchRecords__typeInfo, matchRecords, matchRecords__is_set);
       __typeMapper.writeString(__out, rule__typeInfo, rule, rule__is_set);
       __typeMapper.writeInt(__out, size__typeInfo, size, size__is_set);
       __typeMapper.writeBoolean(__out, success__typeInfo, success, success__is_set);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        setErrors(__in, __typeMapper);
        setEntityType(__in, __typeMapper);
        setMatchEngine(__in, __typeMapper);
        setMatchRecords(__in, __typeMapper);
        setRule(__in, __typeMapper);
        setSize(__in, __typeMapper);
        setSuccess(__in, __typeMapper);
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[MatchResult ");
      sb.append(" errors='").append(com.sforce.ws.util.Verbose.toString(errors)).append("'\n");
      sb.append(" entityType='").append(com.sforce.ws.util.Verbose.toString(entityType)).append("'\n");
      sb.append(" matchEngine='").append(com.sforce.ws.util.Verbose.toString(matchEngine)).append("'\n");
      sb.append(" matchRecords='").append(com.sforce.ws.util.Verbose.toString(matchRecords)).append("'\n");
      sb.append(" rule='").append(com.sforce.ws.util.Verbose.toString(rule)).append("'\n");
      sb.append(" size='").append(com.sforce.ws.util.Verbose.toString(size)).append("'\n");
      sb.append(" success='").append(com.sforce.ws.util.Verbose.toString(success)).append("'\n");
      sb.append("]\n");
      return sb.toString();
    }

    @SuppressWarnings("unchecked")
    private <T,U> T[] castArray(Class<T> clazz, U[] array) {
        if (array == null) {
            return null;
        }
        T[] retVal = (T[]) java.lang.reflect.Array.newInstance(clazz, array.length);
        for (int i=0; i < array.length; i++) {
            retVal[i] = (T)array[i];
        }

        return retVal;
	}
}
