package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public class PerformQuickActionResult implements com.sforce.ws.bind.XMLizable , IPerformQuickActionResult{

    /**
     * Constructor
     */
    public PerformQuickActionResult() {}

    /**
     * element : contextId of type {urn:partner.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo contextId__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","contextId","urn:partner.soap.sforce.com","ID",0,1,true);

    private boolean contextId__is_set = false;

    private java.lang.String contextId;

    @Override
    public java.lang.String getContextId() {
      return contextId;
    }

    @Override
    public void setContextId(java.lang.String contextId) {
      this.contextId = contextId;
      contextId__is_set = true;
    }

    protected void setContextId(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, contextId__typeInfo)) {
        setContextId(__typeMapper.readString(__in, contextId__typeInfo, java.lang.String.class));
      }
    }

    /**
     * element : created of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private static final com.sforce.ws.bind.TypeInfo created__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","created","http://www.w3.org/2001/XMLSchema","boolean",1,1,true);

    private boolean created__is_set = false;

    private boolean created;

    @Override
    public boolean getCreated() {
      return created;
    }

    @Override
    public boolean isCreated() {
      return created;
    }

    @Override
    public void setCreated(boolean created) {
      this.created = created;
      created__is_set = true;
    }

    protected void setCreated(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, created__typeInfo)) {
        setCreated(__typeMapper.readBoolean(__in, created__typeInfo, boolean.class));
      }
    }

    /**
     * element : errors of type {urn:partner.soap.sforce.com}Error
     * java type: com.sforce.soap.partner.Error[]
     */
    private static final com.sforce.ws.bind.TypeInfo errors__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","errors","urn:partner.soap.sforce.com","Error",0,-1,true);

    private boolean errors__is_set = false;

    private com.sforce.soap.partner.Error[] errors = new com.sforce.soap.partner.Error[0];

    @Override
    public com.sforce.soap.partner.Error[] getErrors() {
      return errors;
    }

    @Override
    public void setErrors(com.sforce.soap.partner.IError[] errors) {
      this.errors = castArray(com.sforce.soap.partner.Error.class, errors);
      errors__is_set = true;
    }

    protected void setErrors(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, errors__typeInfo)) {
        setErrors((com.sforce.soap.partner.Error[])__typeMapper.readObject(__in, errors__typeInfo, com.sforce.soap.partner.Error[].class));
      }
    }

    /**
     * element : feedItemIds of type {urn:partner.soap.sforce.com}ID
     * java type: java.lang.String[]
     */
    private static final com.sforce.ws.bind.TypeInfo feedItemIds__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","feedItemIds","urn:partner.soap.sforce.com","ID",0,-1,true);

    private boolean feedItemIds__is_set = false;

    private java.lang.String[] feedItemIds = new java.lang.String[0];

    @Override
    public java.lang.String[] getFeedItemIds() {
      return feedItemIds;
    }

    @Override
    public void setFeedItemIds(java.lang.String[] feedItemIds) {
      this.feedItemIds = castArray(java.lang.String.class, feedItemIds);
      feedItemIds__is_set = true;
    }

    protected void setFeedItemIds(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, feedItemIds__typeInfo)) {
        setFeedItemIds((java.lang.String[])__typeMapper.readObject(__in, feedItemIds__typeInfo, java.lang.String[].class));
      }
    }

    /**
     * element : ids of type {urn:partner.soap.sforce.com}ID
     * java type: java.lang.String[]
     */
    private static final com.sforce.ws.bind.TypeInfo ids__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","ids","urn:partner.soap.sforce.com","ID",0,-1,true);

    private boolean ids__is_set = false;

    private java.lang.String[] ids = new java.lang.String[0];

    @Override
    public java.lang.String[] getIds() {
      return ids;
    }

    @Override
    public void setIds(java.lang.String[] ids) {
      this.ids = castArray(java.lang.String.class, ids);
      ids__is_set = true;
    }

    protected void setIds(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, ids__typeInfo)) {
        setIds((java.lang.String[])__typeMapper.readObject(__in, ids__typeInfo, java.lang.String[].class));
      }
    }

    /**
     * element : success of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private static final com.sforce.ws.bind.TypeInfo success__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","success","http://www.w3.org/2001/XMLSchema","boolean",1,1,true);

    private boolean success__is_set = false;

    private boolean success;

    @Override
    public boolean getSuccess() {
      return success;
    }

    @Override
    public boolean isSuccess() {
      return success;
    }

    @Override
    public void setSuccess(boolean success) {
      this.success = success;
      success__is_set = true;
    }

    protected void setSuccess(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, success__typeInfo)) {
        setSuccess(__typeMapper.readBoolean(__in, success__typeInfo, boolean.class));
      }
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       __typeMapper.writeString(__out, contextId__typeInfo, contextId, contextId__is_set);
       __typeMapper.writeBoolean(__out, created__typeInfo, created, created__is_set);
       __typeMapper.writeObject(__out, errors__typeInfo, errors, errors__is_set);
       __typeMapper.writeObject(__out, feedItemIds__typeInfo, feedItemIds, feedItemIds__is_set);
       __typeMapper.writeObject(__out, ids__typeInfo, ids, ids__is_set);
       __typeMapper.writeBoolean(__out, success__typeInfo, success, success__is_set);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        setContextId(__in, __typeMapper);
        setCreated(__in, __typeMapper);
        setErrors(__in, __typeMapper);
        setFeedItemIds(__in, __typeMapper);
        setIds(__in, __typeMapper);
        setSuccess(__in, __typeMapper);
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[PerformQuickActionResult ");
      sb.append(" contextId='").append(com.sforce.ws.util.Verbose.toString(contextId)).append("'\n");
      sb.append(" created='").append(com.sforce.ws.util.Verbose.toString(created)).append("'\n");
      sb.append(" errors='").append(com.sforce.ws.util.Verbose.toString(errors)).append("'\n");
      sb.append(" feedItemIds='").append(com.sforce.ws.util.Verbose.toString(feedItemIds)).append("'\n");
      sb.append(" ids='").append(com.sforce.ws.util.Verbose.toString(ids)).append("'\n");
      sb.append(" success='").append(com.sforce.ws.util.Verbose.toString(success)).append("'\n");
      sb.append("]\n");
      return sb.toString();
    }

    @SuppressWarnings("unchecked")
    private <T,U> T[] castArray(Class<T> clazz, U[] array) {
        if (array == null) {
            return null;
        }
        T[] retVal = (T[]) java.lang.reflect.Array.newInstance(clazz, array.length);
        for (int i=0; i < array.length; i++) {
            retVal[i] = (T)array[i];
        }

        return retVal;
	}
}
