package com.sforce.soap.partner;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public class QuickActionTemplateResult implements com.sforce.ws.bind.XMLizable , IQuickActionTemplateResult{

    /**
     * Constructor
     */
    public QuickActionTemplateResult() {}

    /**
     * element : defaultValueFormulas of type {urn:sobject.partner.soap.sforce.com}sObject
     * java type: com.sforce.soap.partner.sobject.SObject
     */
    private static final com.sforce.ws.bind.TypeInfo defaultValueFormulas__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","defaultValueFormulas","urn:sobject.partner.soap.sforce.com","sObject",1,1,true);

    private boolean defaultValueFormulas__is_set = false;

    private com.sforce.soap.partner.sobject.SObject defaultValueFormulas;

    @Override
    public com.sforce.soap.partner.sobject.SObject getDefaultValueFormulas() {
      return defaultValueFormulas;
    }

    @Override
    public void setDefaultValueFormulas(com.sforce.soap.partner.sobject.ISObject defaultValueFormulas) {
      this.defaultValueFormulas = (com.sforce.soap.partner.sobject.SObject)defaultValueFormulas;
      defaultValueFormulas__is_set = true;
    }

    protected void setDefaultValueFormulas(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, defaultValueFormulas__typeInfo)) {
        setDefaultValueFormulas((com.sforce.soap.partner.sobject.SObject)__typeMapper.readObject(__in, defaultValueFormulas__typeInfo, com.sforce.soap.partner.sobject.SObject.class));
      }
    }

    /**
     * element : defaultValues of type {urn:sobject.partner.soap.sforce.com}sObject
     * java type: com.sforce.soap.partner.sobject.SObject
     */
    private static final com.sforce.ws.bind.TypeInfo defaultValues__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","defaultValues","urn:sobject.partner.soap.sforce.com","sObject",1,1,true);

    private boolean defaultValues__is_set = false;

    private com.sforce.soap.partner.sobject.SObject defaultValues;

    @Override
    public com.sforce.soap.partner.sobject.SObject getDefaultValues() {
      return defaultValues;
    }

    @Override
    public void setDefaultValues(com.sforce.soap.partner.sobject.ISObject defaultValues) {
      this.defaultValues = (com.sforce.soap.partner.sobject.SObject)defaultValues;
      defaultValues__is_set = true;
    }

    protected void setDefaultValues(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, defaultValues__typeInfo)) {
        setDefaultValues((com.sforce.soap.partner.sobject.SObject)__typeMapper.readObject(__in, defaultValues__typeInfo, com.sforce.soap.partner.sobject.SObject.class));
      }
    }

    /**
     * element : errors of type {urn:partner.soap.sforce.com}Error
     * java type: com.sforce.soap.partner.Error[]
     */
    private static final com.sforce.ws.bind.TypeInfo errors__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","errors","urn:partner.soap.sforce.com","Error",0,-1,true);

    private boolean errors__is_set = false;

    private com.sforce.soap.partner.Error[] errors = new com.sforce.soap.partner.Error[0];

    @Override
    public com.sforce.soap.partner.Error[] getErrors() {
      return errors;
    }

    @Override
    public void setErrors(com.sforce.soap.partner.IError[] errors) {
      this.errors = castArray(com.sforce.soap.partner.Error.class, errors);
      errors__is_set = true;
    }

    protected void setErrors(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, errors__typeInfo)) {
        setErrors((com.sforce.soap.partner.Error[])__typeMapper.readObject(__in, errors__typeInfo, com.sforce.soap.partner.Error[].class));
      }
    }

    /**
     * element : success of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private static final com.sforce.ws.bind.TypeInfo success__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","success","http://www.w3.org/2001/XMLSchema","boolean",1,1,true);

    private boolean success__is_set = false;

    private boolean success;

    @Override
    public boolean getSuccess() {
      return success;
    }

    @Override
    public boolean isSuccess() {
      return success;
    }

    @Override
    public void setSuccess(boolean success) {
      this.success = success;
      success__is_set = true;
    }

    protected void setSuccess(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, success__typeInfo)) {
        setSuccess(__typeMapper.readBoolean(__in, success__typeInfo, boolean.class));
      }
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       __typeMapper.writeObject(__out, defaultValueFormulas__typeInfo, defaultValueFormulas, defaultValueFormulas__is_set);
       __typeMapper.writeObject(__out, defaultValues__typeInfo, defaultValues, defaultValues__is_set);
       __typeMapper.writeObject(__out, errors__typeInfo, errors, errors__is_set);
       __typeMapper.writeBoolean(__out, success__typeInfo, success, success__is_set);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        setDefaultValueFormulas(__in, __typeMapper);
        setDefaultValues(__in, __typeMapper);
        setErrors(__in, __typeMapper);
        setSuccess(__in, __typeMapper);
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[QuickActionTemplateResult ");
      sb.append(" defaultValueFormulas='").append(com.sforce.ws.util.Verbose.toString(defaultValueFormulas)).append("'\n");
      sb.append(" defaultValues='").append(com.sforce.ws.util.Verbose.toString(defaultValues)).append("'\n");
      sb.append(" errors='").append(com.sforce.ws.util.Verbose.toString(errors)).append("'\n");
      sb.append(" success='").append(com.sforce.ws.util.Verbose.toString(success)).append("'\n");
      sb.append("]\n");
      return sb.toString();
    }

    @SuppressWarnings("unchecked")
    private <T,U> T[] castArray(Class<T> clazz, U[] array) {
        if (array == null) {
            return null;
        }
        T[] retVal = (T[]) java.lang.reflect.Array.newInstance(clazz, array.length);
        for (int i=0; i < array.length; i++) {
            retVal[i] = (T)array[i];
        }

        return retVal;
	}
}
