package com.sforce.soap.partner.fault;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public interface IApiQueryFault extends com.sforce.soap.partner.fault.IApiFault {

      /**
       * element : row of type {http://www.w3.org/2001/XMLSchema}int
       * java type: int
       */

      public int getRow();

      public void setRow(int row);

      /**
       * element : column of type {http://www.w3.org/2001/XMLSchema}int
       * java type: int
       */

      public int getColumn();

      public void setColumn(int column);


}
